// Code generated by ent, DO NOT EDIT.

package accesspolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accesspolicy type in the database.
	Label = "access_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIPBurst10s holds the string denoting the ip_burst_10s field in the database.
	FieldIPBurst10s = "ip_burst_10s"
	// FieldIPBurst60s holds the string denoting the ip_burst_60s field in the database.
	FieldIPBurst60s = "ip_burst_60s"
	// FieldNameBurst10s holds the string denoting the name_burst_10s field in the database.
	FieldNameBurst10s = "name_burst_10s"
	// FieldNameBurst60s holds the string denoting the name_burst_60s field in the database.
	FieldNameBurst60s = "name_burst_60s"
	// FieldDenyFirst holds the string denoting the deny_first field in the database.
	FieldDenyFirst = "deny_first"
	// FieldKickMessage holds the string denoting the kick_message field in the database.
	FieldKickMessage = "kick_message"
	// FieldGeoMode holds the string denoting the geo_mode field in the database.
	FieldGeoMode = "geo_mode"
	// FieldGeoList holds the string denoting the geo_list field in the database.
	FieldGeoList = "geo_list"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeServer holds the string denoting the server edge name in mutations.
	EdgeServer = "server"
	// Table holds the table name of the accesspolicy in the database.
	Table = "access_policies"
	// ServerTable is the table that holds the server relation/edge.
	ServerTable = "access_policies"
	// ServerInverseTable is the table name for the Server entity.
	// It exists in this package in order to avoid circular dependency with the "server" package.
	ServerInverseTable = "servers"
	// ServerColumn is the table column denoting the server relation/edge.
	ServerColumn = "server_policies"
)

// Columns holds all SQL columns for accesspolicy fields.
var Columns = []string{
	FieldID,
	FieldIPBurst10s,
	FieldIPBurst60s,
	FieldNameBurst10s,
	FieldNameBurst60s,
	FieldDenyFirst,
	FieldKickMessage,
	FieldGeoMode,
	FieldGeoList,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "access_policies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"server_policies",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIPBurst10s holds the default value on creation for the "ip_burst_10s" field.
	DefaultIPBurst10s int
	// DefaultIPBurst60s holds the default value on creation for the "ip_burst_60s" field.
	DefaultIPBurst60s int
	// DefaultNameBurst10s holds the default value on creation for the "name_burst_10s" field.
	DefaultNameBurst10s int
	// DefaultNameBurst60s holds the default value on creation for the "name_burst_60s" field.
	DefaultNameBurst60s int
	// DefaultDenyFirst holds the default value on creation for the "deny_first" field.
	DefaultDenyFirst bool
	// DefaultKickMessage holds the default value on creation for the "kick_message" field.
	DefaultKickMessage string
	// DefaultGeoMode holds the default value on creation for the "geo_mode" field.
	DefaultGeoMode string
	// DefaultGeoList holds the default value on creation for the "geo_list" field.
	DefaultGeoList []string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AccessPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIPBurst10s orders the results by the ip_burst_10s field.
func ByIPBurst10s(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPBurst10s, opts...).ToFunc()
}

// ByIPBurst60s orders the results by the ip_burst_60s field.
func ByIPBurst60s(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPBurst60s, opts...).ToFunc()
}

// ByNameBurst10s orders the results by the name_burst_10s field.
func ByNameBurst10s(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameBurst10s, opts...).ToFunc()
}

// ByNameBurst60s orders the results by the name_burst_60s field.
func ByNameBurst60s(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameBurst60s, opts...).ToFunc()
}

// ByDenyFirst orders the results by the deny_first field.
func ByDenyFirst(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDenyFirst, opts...).ToFunc()
}

// ByKickMessage orders the results by the kick_message field.
func ByKickMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKickMessage, opts...).ToFunc()
}

// ByGeoMode orders the results by the geo_mode field.
func ByGeoMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeoMode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByServerField orders the results by server field.
func ByServerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServerStep(), sql.OrderByField(field, opts...))
	}
}
func newServerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
	)
}
