// Code generated by ent, DO NOT EDIT.

package accesspolicy

import (
	"mcproxy/internal/ent/internal"
	"mcproxy/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldID, id))
}

// IPBurst10s applies equality check predicate on the "ip_burst_10s" field. It's identical to IPBurst10sEQ.
func IPBurst10s(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldIPBurst10s, v))
}

// IPBurst60s applies equality check predicate on the "ip_burst_60s" field. It's identical to IPBurst60sEQ.
func IPBurst60s(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldIPBurst60s, v))
}

// NameBurst10s applies equality check predicate on the "name_burst_10s" field. It's identical to NameBurst10sEQ.
func NameBurst10s(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldNameBurst10s, v))
}

// NameBurst60s applies equality check predicate on the "name_burst_60s" field. It's identical to NameBurst60sEQ.
func NameBurst60s(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldNameBurst60s, v))
}

// DenyFirst applies equality check predicate on the "deny_first" field. It's identical to DenyFirstEQ.
func DenyFirst(v bool) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldDenyFirst, v))
}

// KickMessage applies equality check predicate on the "kick_message" field. It's identical to KickMessageEQ.
func KickMessage(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldKickMessage, v))
}

// GeoMode applies equality check predicate on the "geo_mode" field. It's identical to GeoModeEQ.
func GeoMode(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldGeoMode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// IPBurst10sEQ applies the EQ predicate on the "ip_burst_10s" field.
func IPBurst10sEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldIPBurst10s, v))
}

// IPBurst10sNEQ applies the NEQ predicate on the "ip_burst_10s" field.
func IPBurst10sNEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldIPBurst10s, v))
}

// IPBurst10sIn applies the In predicate on the "ip_burst_10s" field.
func IPBurst10sIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldIPBurst10s, vs...))
}

// IPBurst10sNotIn applies the NotIn predicate on the "ip_burst_10s" field.
func IPBurst10sNotIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldIPBurst10s, vs...))
}

// IPBurst10sGT applies the GT predicate on the "ip_burst_10s" field.
func IPBurst10sGT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldIPBurst10s, v))
}

// IPBurst10sGTE applies the GTE predicate on the "ip_burst_10s" field.
func IPBurst10sGTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldIPBurst10s, v))
}

// IPBurst10sLT applies the LT predicate on the "ip_burst_10s" field.
func IPBurst10sLT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldIPBurst10s, v))
}

// IPBurst10sLTE applies the LTE predicate on the "ip_burst_10s" field.
func IPBurst10sLTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldIPBurst10s, v))
}

// IPBurst60sEQ applies the EQ predicate on the "ip_burst_60s" field.
func IPBurst60sEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldIPBurst60s, v))
}

// IPBurst60sNEQ applies the NEQ predicate on the "ip_burst_60s" field.
func IPBurst60sNEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldIPBurst60s, v))
}

// IPBurst60sIn applies the In predicate on the "ip_burst_60s" field.
func IPBurst60sIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldIPBurst60s, vs...))
}

// IPBurst60sNotIn applies the NotIn predicate on the "ip_burst_60s" field.
func IPBurst60sNotIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldIPBurst60s, vs...))
}

// IPBurst60sGT applies the GT predicate on the "ip_burst_60s" field.
func IPBurst60sGT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldIPBurst60s, v))
}

// IPBurst60sGTE applies the GTE predicate on the "ip_burst_60s" field.
func IPBurst60sGTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldIPBurst60s, v))
}

// IPBurst60sLT applies the LT predicate on the "ip_burst_60s" field.
func IPBurst60sLT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldIPBurst60s, v))
}

// IPBurst60sLTE applies the LTE predicate on the "ip_burst_60s" field.
func IPBurst60sLTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldIPBurst60s, v))
}

// NameBurst10sEQ applies the EQ predicate on the "name_burst_10s" field.
func NameBurst10sEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldNameBurst10s, v))
}

// NameBurst10sNEQ applies the NEQ predicate on the "name_burst_10s" field.
func NameBurst10sNEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldNameBurst10s, v))
}

// NameBurst10sIn applies the In predicate on the "name_burst_10s" field.
func NameBurst10sIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldNameBurst10s, vs...))
}

// NameBurst10sNotIn applies the NotIn predicate on the "name_burst_10s" field.
func NameBurst10sNotIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldNameBurst10s, vs...))
}

// NameBurst10sGT applies the GT predicate on the "name_burst_10s" field.
func NameBurst10sGT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldNameBurst10s, v))
}

// NameBurst10sGTE applies the GTE predicate on the "name_burst_10s" field.
func NameBurst10sGTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldNameBurst10s, v))
}

// NameBurst10sLT applies the LT predicate on the "name_burst_10s" field.
func NameBurst10sLT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldNameBurst10s, v))
}

// NameBurst10sLTE applies the LTE predicate on the "name_burst_10s" field.
func NameBurst10sLTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldNameBurst10s, v))
}

// NameBurst60sEQ applies the EQ predicate on the "name_burst_60s" field.
func NameBurst60sEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldNameBurst60s, v))
}

// NameBurst60sNEQ applies the NEQ predicate on the "name_burst_60s" field.
func NameBurst60sNEQ(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldNameBurst60s, v))
}

// NameBurst60sIn applies the In predicate on the "name_burst_60s" field.
func NameBurst60sIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldNameBurst60s, vs...))
}

// NameBurst60sNotIn applies the NotIn predicate on the "name_burst_60s" field.
func NameBurst60sNotIn(vs ...int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldNameBurst60s, vs...))
}

// NameBurst60sGT applies the GT predicate on the "name_burst_60s" field.
func NameBurst60sGT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldNameBurst60s, v))
}

// NameBurst60sGTE applies the GTE predicate on the "name_burst_60s" field.
func NameBurst60sGTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldNameBurst60s, v))
}

// NameBurst60sLT applies the LT predicate on the "name_burst_60s" field.
func NameBurst60sLT(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldNameBurst60s, v))
}

// NameBurst60sLTE applies the LTE predicate on the "name_burst_60s" field.
func NameBurst60sLTE(v int) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldNameBurst60s, v))
}

// DenyFirstEQ applies the EQ predicate on the "deny_first" field.
func DenyFirstEQ(v bool) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldDenyFirst, v))
}

// DenyFirstNEQ applies the NEQ predicate on the "deny_first" field.
func DenyFirstNEQ(v bool) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldDenyFirst, v))
}

// KickMessageEQ applies the EQ predicate on the "kick_message" field.
func KickMessageEQ(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldKickMessage, v))
}

// KickMessageNEQ applies the NEQ predicate on the "kick_message" field.
func KickMessageNEQ(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldKickMessage, v))
}

// KickMessageIn applies the In predicate on the "kick_message" field.
func KickMessageIn(vs ...string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldKickMessage, vs...))
}

// KickMessageNotIn applies the NotIn predicate on the "kick_message" field.
func KickMessageNotIn(vs ...string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldKickMessage, vs...))
}

// KickMessageGT applies the GT predicate on the "kick_message" field.
func KickMessageGT(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldKickMessage, v))
}

// KickMessageGTE applies the GTE predicate on the "kick_message" field.
func KickMessageGTE(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldKickMessage, v))
}

// KickMessageLT applies the LT predicate on the "kick_message" field.
func KickMessageLT(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldKickMessage, v))
}

// KickMessageLTE applies the LTE predicate on the "kick_message" field.
func KickMessageLTE(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldKickMessage, v))
}

// KickMessageContains applies the Contains predicate on the "kick_message" field.
func KickMessageContains(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldContains(FieldKickMessage, v))
}

// KickMessageHasPrefix applies the HasPrefix predicate on the "kick_message" field.
func KickMessageHasPrefix(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldHasPrefix(FieldKickMessage, v))
}

// KickMessageHasSuffix applies the HasSuffix predicate on the "kick_message" field.
func KickMessageHasSuffix(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldHasSuffix(FieldKickMessage, v))
}

// KickMessageEqualFold applies the EqualFold predicate on the "kick_message" field.
func KickMessageEqualFold(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEqualFold(FieldKickMessage, v))
}

// KickMessageContainsFold applies the ContainsFold predicate on the "kick_message" field.
func KickMessageContainsFold(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldContainsFold(FieldKickMessage, v))
}

// GeoModeEQ applies the EQ predicate on the "geo_mode" field.
func GeoModeEQ(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldGeoMode, v))
}

// GeoModeNEQ applies the NEQ predicate on the "geo_mode" field.
func GeoModeNEQ(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldGeoMode, v))
}

// GeoModeIn applies the In predicate on the "geo_mode" field.
func GeoModeIn(vs ...string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldGeoMode, vs...))
}

// GeoModeNotIn applies the NotIn predicate on the "geo_mode" field.
func GeoModeNotIn(vs ...string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldGeoMode, vs...))
}

// GeoModeGT applies the GT predicate on the "geo_mode" field.
func GeoModeGT(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldGeoMode, v))
}

// GeoModeGTE applies the GTE predicate on the "geo_mode" field.
func GeoModeGTE(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldGeoMode, v))
}

// GeoModeLT applies the LT predicate on the "geo_mode" field.
func GeoModeLT(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldGeoMode, v))
}

// GeoModeLTE applies the LTE predicate on the "geo_mode" field.
func GeoModeLTE(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldGeoMode, v))
}

// GeoModeContains applies the Contains predicate on the "geo_mode" field.
func GeoModeContains(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldContains(FieldGeoMode, v))
}

// GeoModeHasPrefix applies the HasPrefix predicate on the "geo_mode" field.
func GeoModeHasPrefix(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldHasPrefix(FieldGeoMode, v))
}

// GeoModeHasSuffix applies the HasSuffix predicate on the "geo_mode" field.
func GeoModeHasSuffix(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldHasSuffix(FieldGeoMode, v))
}

// GeoModeEqualFold applies the EqualFold predicate on the "geo_mode" field.
func GeoModeEqualFold(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEqualFold(FieldGeoMode, v))
}

// GeoModeContainsFold applies the ContainsFold predicate on the "geo_mode" field.
func GeoModeContainsFold(v string) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldContainsFold(FieldGeoMode, v))
}

// GeoListIsNil applies the IsNil predicate on the "geo_list" field.
func GeoListIsNil() predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIsNull(FieldGeoList))
}

// GeoListNotNil applies the NotNil predicate on the "geo_list" field.
func GeoListNotNil() predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotNull(FieldGeoList))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasServer applies the HasEdge predicate on the "server" edge.
func HasServer() predicate.AccessPolicy {
	return predicate.AccessPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Server
		step.Edge.Schema = schemaConfig.AccessPolicy
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerWith applies the HasEdge predicate on the "server" edge with a given conditions (other predicates).
func HasServerWith(preds ...predicate.Server) predicate.AccessPolicy {
	return predicate.AccessPolicy(func(s *sql.Selector) {
		step := newServerStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Server
		step.Edge.Schema = schemaConfig.AccessPolicy
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessPolicy) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessPolicy) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessPolicy) predicate.AccessPolicy {
	return predicate.AccessPolicy(sql.NotPredicates(p))
}
