// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessPoliciesColumns holds the columns for the "access_policies" table.
	AccessPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip_burst_10s", Type: field.TypeInt, Default: 20},
		{Name: "ip_burst_60s", Type: field.TypeInt, Default: 80},
		{Name: "name_burst_10s", Type: field.TypeInt, Default: 15},
		{Name: "name_burst_60s", Type: field.TypeInt, Default: 60},
		{Name: "deny_first", Type: field.TypeBool, Default: false},
		{Name: "kick_message", Type: field.TypeString, Default: "Connection denied by policy"},
		{Name: "geo_mode", Type: field.TypeString, Default: "disabled"},
		{Name: "geo_list", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_policies", Type: field.TypeInt, Nullable: true},
	}
	// AccessPoliciesTable holds the schema information for the "access_policies" table.
	AccessPoliciesTable = &schema.Table{
		Name:       "access_policies",
		Columns:    AccessPoliciesColumns,
		PrimaryKey: []*schema.Column{AccessPoliciesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "access_policies_servers_policies",
				Columns:    []*schema.Column{AccessPoliciesColumns[11]},
				RefColumns: []*schema.Column{ServersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AuditsColumns holds the columns for the "audits" table.
	AuditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event", Type: field.TypeString},
		{Name: "actor", Type: field.TypeString, Nullable: true},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "server_audits", Type: field.TypeInt, Nullable: true},
	}
	// AuditsTable holds the schema information for the "audits" table.
	AuditsTable = &schema.Table{
		Name:       "audits",
		Columns:    AuditsColumns,
		PrimaryKey: []*schema.Column{AuditsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audits_servers_audits",
				Columns:    []*schema.Column{AuditsColumns[5]},
				RefColumns: []*schema.Column{ServersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CountersColumns holds the columns for the "counters" table.
	CountersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "window_sec", Type: field.TypeInt},
		{Name: "count", Type: field.TypeInt, Default: 0},
		{Name: "last_seen", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_counters", Type: field.TypeInt, Nullable: true},
	}
	// CountersTable holds the schema information for the "counters" table.
	CountersTable = &schema.Table{
		Name:       "counters",
		Columns:    CountersColumns,
		PrimaryKey: []*schema.Column{CountersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "counters_servers_counters",
				Columns:    []*schema.Column{CountersColumns[8]},
				RefColumns: []*schema.Column{ServersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RulesColumns holds the columns for the "rules" table.
	RulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "target", Type: field.TypeString},
		{Name: "is_cidr", Type: field.TypeBool, Default: false},
		{Name: "reason", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "server_rules", Type: field.TypeInt, Nullable: true},
	}
	// RulesTable holds the schema information for the "rules" table.
	RulesTable = &schema.Table{
		Name:       "rules",
		Columns:    RulesColumns,
		PrimaryKey: []*schema.Column{RulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rules_servers_rules",
				Columns:    []*schema.Column{RulesColumns[9]},
				RefColumns: []*schema.Column{ServersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ServersColumns holds the columns for the "servers" table.
	ServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "upstream", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ServersTable holds the schema information for the "servers" table.
	ServersTable = &schema.Table{
		Name:       "servers",
		Columns:    ServersColumns,
		PrimaryKey: []*schema.Column{ServersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessPoliciesTable,
		AuditsTable,
		CountersTable,
		RulesTable,
		ServersTable,
	}
)

func init() {
	AccessPoliciesTable.ForeignKeys[0].RefTable = ServersTable
	AuditsTable.ForeignKeys[0].RefTable = ServersTable
	CountersTable.ForeignKeys[0].RefTable = ServersTable
	RulesTable.ForeignKeys[0].RefTable = ServersTable
}
