// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/accesspolicy"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessPolicyCreate is the builder for creating a AccessPolicy entity.
type AccessPolicyCreate struct {
	config
	mutation *AccessPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIPBurst10s sets the "ip_burst_10s" field.
func (_c *AccessPolicyCreate) SetIPBurst10s(v int) *AccessPolicyCreate {
	_c.mutation.SetIPBurst10s(v)
	return _c
}

// SetNillableIPBurst10s sets the "ip_burst_10s" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableIPBurst10s(v *int) *AccessPolicyCreate {
	if v != nil {
		_c.SetIPBurst10s(*v)
	}
	return _c
}

// SetIPBurst60s sets the "ip_burst_60s" field.
func (_c *AccessPolicyCreate) SetIPBurst60s(v int) *AccessPolicyCreate {
	_c.mutation.SetIPBurst60s(v)
	return _c
}

// SetNillableIPBurst60s sets the "ip_burst_60s" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableIPBurst60s(v *int) *AccessPolicyCreate {
	if v != nil {
		_c.SetIPBurst60s(*v)
	}
	return _c
}

// SetNameBurst10s sets the "name_burst_10s" field.
func (_c *AccessPolicyCreate) SetNameBurst10s(v int) *AccessPolicyCreate {
	_c.mutation.SetNameBurst10s(v)
	return _c
}

// SetNillableNameBurst10s sets the "name_burst_10s" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableNameBurst10s(v *int) *AccessPolicyCreate {
	if v != nil {
		_c.SetNameBurst10s(*v)
	}
	return _c
}

// SetNameBurst60s sets the "name_burst_60s" field.
func (_c *AccessPolicyCreate) SetNameBurst60s(v int) *AccessPolicyCreate {
	_c.mutation.SetNameBurst60s(v)
	return _c
}

// SetNillableNameBurst60s sets the "name_burst_60s" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableNameBurst60s(v *int) *AccessPolicyCreate {
	if v != nil {
		_c.SetNameBurst60s(*v)
	}
	return _c
}

// SetDenyFirst sets the "deny_first" field.
func (_c *AccessPolicyCreate) SetDenyFirst(v bool) *AccessPolicyCreate {
	_c.mutation.SetDenyFirst(v)
	return _c
}

// SetNillableDenyFirst sets the "deny_first" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableDenyFirst(v *bool) *AccessPolicyCreate {
	if v != nil {
		_c.SetDenyFirst(*v)
	}
	return _c
}

// SetKickMessage sets the "kick_message" field.
func (_c *AccessPolicyCreate) SetKickMessage(v string) *AccessPolicyCreate {
	_c.mutation.SetKickMessage(v)
	return _c
}

// SetNillableKickMessage sets the "kick_message" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableKickMessage(v *string) *AccessPolicyCreate {
	if v != nil {
		_c.SetKickMessage(*v)
	}
	return _c
}

// SetGeoMode sets the "geo_mode" field.
func (_c *AccessPolicyCreate) SetGeoMode(v string) *AccessPolicyCreate {
	_c.mutation.SetGeoMode(v)
	return _c
}

// SetNillableGeoMode sets the "geo_mode" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableGeoMode(v *string) *AccessPolicyCreate {
	if v != nil {
		_c.SetGeoMode(*v)
	}
	return _c
}

// SetGeoList sets the "geo_list" field.
func (_c *AccessPolicyCreate) SetGeoList(v []string) *AccessPolicyCreate {
	_c.mutation.SetGeoList(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessPolicyCreate) SetCreatedAt(v time.Time) *AccessPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableCreatedAt(v *time.Time) *AccessPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccessPolicyCreate) SetUpdatedAt(v time.Time) *AccessPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableUpdatedAt(v *time.Time) *AccessPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_c *AccessPolicyCreate) SetServerID(id int) *AccessPolicyCreate {
	_c.mutation.SetServerID(id)
	return _c
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableServerID(id *int) *AccessPolicyCreate {
	if id != nil {
		_c = _c.SetServerID(*id)
	}
	return _c
}

// SetServer sets the "server" edge to the Server entity.
func (_c *AccessPolicyCreate) SetServer(v *Server) *AccessPolicyCreate {
	return _c.SetServerID(v.ID)
}

// Mutation returns the AccessPolicyMutation object of the builder.
func (_c *AccessPolicyCreate) Mutation() *AccessPolicyMutation {
	return _c.mutation
}

// Save creates the AccessPolicy in the database.
func (_c *AccessPolicyCreate) Save(ctx context.Context) (*AccessPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessPolicyCreate) SaveX(ctx context.Context) *AccessPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessPolicyCreate) defaults() {
	if _, ok := _c.mutation.IPBurst10s(); !ok {
		v := accesspolicy.DefaultIPBurst10s
		_c.mutation.SetIPBurst10s(v)
	}
	if _, ok := _c.mutation.IPBurst60s(); !ok {
		v := accesspolicy.DefaultIPBurst60s
		_c.mutation.SetIPBurst60s(v)
	}
	if _, ok := _c.mutation.NameBurst10s(); !ok {
		v := accesspolicy.DefaultNameBurst10s
		_c.mutation.SetNameBurst10s(v)
	}
	if _, ok := _c.mutation.NameBurst60s(); !ok {
		v := accesspolicy.DefaultNameBurst60s
		_c.mutation.SetNameBurst60s(v)
	}
	if _, ok := _c.mutation.DenyFirst(); !ok {
		v := accesspolicy.DefaultDenyFirst
		_c.mutation.SetDenyFirst(v)
	}
	if _, ok := _c.mutation.KickMessage(); !ok {
		v := accesspolicy.DefaultKickMessage
		_c.mutation.SetKickMessage(v)
	}
	if _, ok := _c.mutation.GeoMode(); !ok {
		v := accesspolicy.DefaultGeoMode
		_c.mutation.SetGeoMode(v)
	}
	if _, ok := _c.mutation.GeoList(); !ok {
		v := accesspolicy.DefaultGeoList
		_c.mutation.SetGeoList(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accesspolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accesspolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessPolicyCreate) check() error {
	if _, ok := _c.mutation.IPBurst10s(); !ok {
		return &ValidationError{Name: "ip_burst_10s", err: errors.New(`ent: missing required field "AccessPolicy.ip_burst_10s"`)}
	}
	if _, ok := _c.mutation.IPBurst60s(); !ok {
		return &ValidationError{Name: "ip_burst_60s", err: errors.New(`ent: missing required field "AccessPolicy.ip_burst_60s"`)}
	}
	if _, ok := _c.mutation.NameBurst10s(); !ok {
		return &ValidationError{Name: "name_burst_10s", err: errors.New(`ent: missing required field "AccessPolicy.name_burst_10s"`)}
	}
	if _, ok := _c.mutation.NameBurst60s(); !ok {
		return &ValidationError{Name: "name_burst_60s", err: errors.New(`ent: missing required field "AccessPolicy.name_burst_60s"`)}
	}
	if _, ok := _c.mutation.DenyFirst(); !ok {
		return &ValidationError{Name: "deny_first", err: errors.New(`ent: missing required field "AccessPolicy.deny_first"`)}
	}
	if _, ok := _c.mutation.KickMessage(); !ok {
		return &ValidationError{Name: "kick_message", err: errors.New(`ent: missing required field "AccessPolicy.kick_message"`)}
	}
	if _, ok := _c.mutation.GeoMode(); !ok {
		return &ValidationError{Name: "geo_mode", err: errors.New(`ent: missing required field "AccessPolicy.geo_mode"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccessPolicy.updated_at"`)}
	}
	return nil
}

func (_c *AccessPolicyCreate) sqlSave(ctx context.Context) (*AccessPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessPolicyCreate) createSpec() (*AccessPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesspolicy.Table, sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.AccessPolicy
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.IPBurst10s(); ok {
		_spec.SetField(accesspolicy.FieldIPBurst10s, field.TypeInt, value)
		_node.IPBurst10s = value
	}
	if value, ok := _c.mutation.IPBurst60s(); ok {
		_spec.SetField(accesspolicy.FieldIPBurst60s, field.TypeInt, value)
		_node.IPBurst60s = value
	}
	if value, ok := _c.mutation.NameBurst10s(); ok {
		_spec.SetField(accesspolicy.FieldNameBurst10s, field.TypeInt, value)
		_node.NameBurst10s = value
	}
	if value, ok := _c.mutation.NameBurst60s(); ok {
		_spec.SetField(accesspolicy.FieldNameBurst60s, field.TypeInt, value)
		_node.NameBurst60s = value
	}
	if value, ok := _c.mutation.DenyFirst(); ok {
		_spec.SetField(accesspolicy.FieldDenyFirst, field.TypeBool, value)
		_node.DenyFirst = value
	}
	if value, ok := _c.mutation.KickMessage(); ok {
		_spec.SetField(accesspolicy.FieldKickMessage, field.TypeString, value)
		_node.KickMessage = value
	}
	if value, ok := _c.mutation.GeoMode(); ok {
		_spec.SetField(accesspolicy.FieldGeoMode, field.TypeString, value)
		_node.GeoMode = value
	}
	if value, ok := _c.mutation.GeoList(); ok {
		_spec.SetField(accesspolicy.FieldGeoList, field.TypeJSON, value)
		_node.GeoList = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accesspolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accesspolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesspolicy.ServerTable,
			Columns: []string{accesspolicy.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.server_policies = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccessPolicy.Create().
//		SetIPBurst10s(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccessPolicyUpsert) {
//			SetIPBurst10s(v+v).
//		}).
//		Exec(ctx)
func (_c *AccessPolicyCreate) OnConflict(opts ...sql.ConflictOption) *AccessPolicyUpsertOne {
	_c.conflict = opts
	return &AccessPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccessPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccessPolicyCreate) OnConflictColumns(columns ...string) *AccessPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccessPolicyUpsertOne{
		create: _c,
	}
}

type (
	// AccessPolicyUpsertOne is the builder for "upsert"-ing
	//  one AccessPolicy node.
	AccessPolicyUpsertOne struct {
		create *AccessPolicyCreate
	}

	// AccessPolicyUpsert is the "OnConflict" setter.
	AccessPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetIPBurst10s sets the "ip_burst_10s" field.
func (u *AccessPolicyUpsert) SetIPBurst10s(v int) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldIPBurst10s, v)
	return u
}

// UpdateIPBurst10s sets the "ip_burst_10s" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateIPBurst10s() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldIPBurst10s)
	return u
}

// AddIPBurst10s adds v to the "ip_burst_10s" field.
func (u *AccessPolicyUpsert) AddIPBurst10s(v int) *AccessPolicyUpsert {
	u.Add(accesspolicy.FieldIPBurst10s, v)
	return u
}

// SetIPBurst60s sets the "ip_burst_60s" field.
func (u *AccessPolicyUpsert) SetIPBurst60s(v int) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldIPBurst60s, v)
	return u
}

// UpdateIPBurst60s sets the "ip_burst_60s" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateIPBurst60s() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldIPBurst60s)
	return u
}

// AddIPBurst60s adds v to the "ip_burst_60s" field.
func (u *AccessPolicyUpsert) AddIPBurst60s(v int) *AccessPolicyUpsert {
	u.Add(accesspolicy.FieldIPBurst60s, v)
	return u
}

// SetNameBurst10s sets the "name_burst_10s" field.
func (u *AccessPolicyUpsert) SetNameBurst10s(v int) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldNameBurst10s, v)
	return u
}

// UpdateNameBurst10s sets the "name_burst_10s" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateNameBurst10s() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldNameBurst10s)
	return u
}

// AddNameBurst10s adds v to the "name_burst_10s" field.
func (u *AccessPolicyUpsert) AddNameBurst10s(v int) *AccessPolicyUpsert {
	u.Add(accesspolicy.FieldNameBurst10s, v)
	return u
}

// SetNameBurst60s sets the "name_burst_60s" field.
func (u *AccessPolicyUpsert) SetNameBurst60s(v int) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldNameBurst60s, v)
	return u
}

// UpdateNameBurst60s sets the "name_burst_60s" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateNameBurst60s() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldNameBurst60s)
	return u
}

// AddNameBurst60s adds v to the "name_burst_60s" field.
func (u *AccessPolicyUpsert) AddNameBurst60s(v int) *AccessPolicyUpsert {
	u.Add(accesspolicy.FieldNameBurst60s, v)
	return u
}

// SetDenyFirst sets the "deny_first" field.
func (u *AccessPolicyUpsert) SetDenyFirst(v bool) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldDenyFirst, v)
	return u
}

// UpdateDenyFirst sets the "deny_first" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateDenyFirst() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldDenyFirst)
	return u
}

// SetKickMessage sets the "kick_message" field.
func (u *AccessPolicyUpsert) SetKickMessage(v string) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldKickMessage, v)
	return u
}

// UpdateKickMessage sets the "kick_message" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateKickMessage() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldKickMessage)
	return u
}

// SetGeoMode sets the "geo_mode" field.
func (u *AccessPolicyUpsert) SetGeoMode(v string) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldGeoMode, v)
	return u
}

// UpdateGeoMode sets the "geo_mode" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateGeoMode() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldGeoMode)
	return u
}

// SetGeoList sets the "geo_list" field.
func (u *AccessPolicyUpsert) SetGeoList(v []string) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldGeoList, v)
	return u
}

// UpdateGeoList sets the "geo_list" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateGeoList() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldGeoList)
	return u
}

// ClearGeoList clears the value of the "geo_list" field.
func (u *AccessPolicyUpsert) ClearGeoList() *AccessPolicyUpsert {
	u.SetNull(accesspolicy.FieldGeoList)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AccessPolicyUpsert) SetCreatedAt(v time.Time) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateCreatedAt() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccessPolicyUpsert) SetUpdatedAt(v time.Time) *AccessPolicyUpsert {
	u.Set(accesspolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccessPolicyUpsert) UpdateUpdatedAt() *AccessPolicyUpsert {
	u.SetExcluded(accesspolicy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccessPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccessPolicyUpsertOne) UpdateNewValues() *AccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccessPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccessPolicyUpsertOne) Ignore() *AccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccessPolicyUpsertOne) DoNothing() *AccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccessPolicyCreate.OnConflict
// documentation for more info.
func (u *AccessPolicyUpsertOne) Update(set func(*AccessPolicyUpsert)) *AccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccessPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetIPBurst10s sets the "ip_burst_10s" field.
func (u *AccessPolicyUpsertOne) SetIPBurst10s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetIPBurst10s(v)
	})
}

// AddIPBurst10s adds v to the "ip_burst_10s" field.
func (u *AccessPolicyUpsertOne) AddIPBurst10s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddIPBurst10s(v)
	})
}

// UpdateIPBurst10s sets the "ip_burst_10s" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateIPBurst10s() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateIPBurst10s()
	})
}

// SetIPBurst60s sets the "ip_burst_60s" field.
func (u *AccessPolicyUpsertOne) SetIPBurst60s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetIPBurst60s(v)
	})
}

// AddIPBurst60s adds v to the "ip_burst_60s" field.
func (u *AccessPolicyUpsertOne) AddIPBurst60s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddIPBurst60s(v)
	})
}

// UpdateIPBurst60s sets the "ip_burst_60s" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateIPBurst60s() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateIPBurst60s()
	})
}

// SetNameBurst10s sets the "name_burst_10s" field.
func (u *AccessPolicyUpsertOne) SetNameBurst10s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetNameBurst10s(v)
	})
}

// AddNameBurst10s adds v to the "name_burst_10s" field.
func (u *AccessPolicyUpsertOne) AddNameBurst10s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddNameBurst10s(v)
	})
}

// UpdateNameBurst10s sets the "name_burst_10s" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateNameBurst10s() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateNameBurst10s()
	})
}

// SetNameBurst60s sets the "name_burst_60s" field.
func (u *AccessPolicyUpsertOne) SetNameBurst60s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetNameBurst60s(v)
	})
}

// AddNameBurst60s adds v to the "name_burst_60s" field.
func (u *AccessPolicyUpsertOne) AddNameBurst60s(v int) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddNameBurst60s(v)
	})
}

// UpdateNameBurst60s sets the "name_burst_60s" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateNameBurst60s() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateNameBurst60s()
	})
}

// SetDenyFirst sets the "deny_first" field.
func (u *AccessPolicyUpsertOne) SetDenyFirst(v bool) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetDenyFirst(v)
	})
}

// UpdateDenyFirst sets the "deny_first" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateDenyFirst() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateDenyFirst()
	})
}

// SetKickMessage sets the "kick_message" field.
func (u *AccessPolicyUpsertOne) SetKickMessage(v string) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetKickMessage(v)
	})
}

// UpdateKickMessage sets the "kick_message" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateKickMessage() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateKickMessage()
	})
}

// SetGeoMode sets the "geo_mode" field.
func (u *AccessPolicyUpsertOne) SetGeoMode(v string) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetGeoMode(v)
	})
}

// UpdateGeoMode sets the "geo_mode" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateGeoMode() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateGeoMode()
	})
}

// SetGeoList sets the "geo_list" field.
func (u *AccessPolicyUpsertOne) SetGeoList(v []string) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetGeoList(v)
	})
}

// UpdateGeoList sets the "geo_list" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateGeoList() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateGeoList()
	})
}

// ClearGeoList clears the value of the "geo_list" field.
func (u *AccessPolicyUpsertOne) ClearGeoList() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.ClearGeoList()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AccessPolicyUpsertOne) SetCreatedAt(v time.Time) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateCreatedAt() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccessPolicyUpsertOne) SetUpdatedAt(v time.Time) *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccessPolicyUpsertOne) UpdateUpdatedAt() *AccessPolicyUpsertOne {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccessPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccessPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccessPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccessPolicyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccessPolicyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccessPolicyCreateBulk is the builder for creating many AccessPolicy entities in bulk.
type AccessPolicyCreateBulk struct {
	config
	err      error
	builders []*AccessPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the AccessPolicy entities in the database.
func (_c *AccessPolicyCreateBulk) Save(ctx context.Context) ([]*AccessPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessPolicyCreateBulk) SaveX(ctx context.Context) []*AccessPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccessPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccessPolicyUpsert) {
//			SetIPBurst10s(v+v).
//		}).
//		Exec(ctx)
func (_c *AccessPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccessPolicyUpsertBulk {
	_c.conflict = opts
	return &AccessPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccessPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccessPolicyCreateBulk) OnConflictColumns(columns ...string) *AccessPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccessPolicyUpsertBulk{
		create: _c,
	}
}

// AccessPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of AccessPolicy nodes.
type AccessPolicyUpsertBulk struct {
	create *AccessPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccessPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccessPolicyUpsertBulk) UpdateNewValues() *AccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccessPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccessPolicyUpsertBulk) Ignore() *AccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccessPolicyUpsertBulk) DoNothing() *AccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccessPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *AccessPolicyUpsertBulk) Update(set func(*AccessPolicyUpsert)) *AccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccessPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetIPBurst10s sets the "ip_burst_10s" field.
func (u *AccessPolicyUpsertBulk) SetIPBurst10s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetIPBurst10s(v)
	})
}

// AddIPBurst10s adds v to the "ip_burst_10s" field.
func (u *AccessPolicyUpsertBulk) AddIPBurst10s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddIPBurst10s(v)
	})
}

// UpdateIPBurst10s sets the "ip_burst_10s" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateIPBurst10s() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateIPBurst10s()
	})
}

// SetIPBurst60s sets the "ip_burst_60s" field.
func (u *AccessPolicyUpsertBulk) SetIPBurst60s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetIPBurst60s(v)
	})
}

// AddIPBurst60s adds v to the "ip_burst_60s" field.
func (u *AccessPolicyUpsertBulk) AddIPBurst60s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddIPBurst60s(v)
	})
}

// UpdateIPBurst60s sets the "ip_burst_60s" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateIPBurst60s() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateIPBurst60s()
	})
}

// SetNameBurst10s sets the "name_burst_10s" field.
func (u *AccessPolicyUpsertBulk) SetNameBurst10s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetNameBurst10s(v)
	})
}

// AddNameBurst10s adds v to the "name_burst_10s" field.
func (u *AccessPolicyUpsertBulk) AddNameBurst10s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddNameBurst10s(v)
	})
}

// UpdateNameBurst10s sets the "name_burst_10s" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateNameBurst10s() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateNameBurst10s()
	})
}

// SetNameBurst60s sets the "name_burst_60s" field.
func (u *AccessPolicyUpsertBulk) SetNameBurst60s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetNameBurst60s(v)
	})
}

// AddNameBurst60s adds v to the "name_burst_60s" field.
func (u *AccessPolicyUpsertBulk) AddNameBurst60s(v int) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.AddNameBurst60s(v)
	})
}

// UpdateNameBurst60s sets the "name_burst_60s" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateNameBurst60s() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateNameBurst60s()
	})
}

// SetDenyFirst sets the "deny_first" field.
func (u *AccessPolicyUpsertBulk) SetDenyFirst(v bool) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetDenyFirst(v)
	})
}

// UpdateDenyFirst sets the "deny_first" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateDenyFirst() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateDenyFirst()
	})
}

// SetKickMessage sets the "kick_message" field.
func (u *AccessPolicyUpsertBulk) SetKickMessage(v string) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetKickMessage(v)
	})
}

// UpdateKickMessage sets the "kick_message" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateKickMessage() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateKickMessage()
	})
}

// SetGeoMode sets the "geo_mode" field.
func (u *AccessPolicyUpsertBulk) SetGeoMode(v string) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetGeoMode(v)
	})
}

// UpdateGeoMode sets the "geo_mode" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateGeoMode() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateGeoMode()
	})
}

// SetGeoList sets the "geo_list" field.
func (u *AccessPolicyUpsertBulk) SetGeoList(v []string) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetGeoList(v)
	})
}

// UpdateGeoList sets the "geo_list" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateGeoList() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateGeoList()
	})
}

// ClearGeoList clears the value of the "geo_list" field.
func (u *AccessPolicyUpsertBulk) ClearGeoList() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.ClearGeoList()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AccessPolicyUpsertBulk) SetCreatedAt(v time.Time) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateCreatedAt() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccessPolicyUpsertBulk) SetUpdatedAt(v time.Time) *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccessPolicyUpsertBulk) UpdateUpdatedAt() *AccessPolicyUpsertBulk {
	return u.Update(func(s *AccessPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccessPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccessPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccessPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccessPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
