// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/accesspolicy"
	"mcproxy/internal/ent/internal"
	"mcproxy/internal/ent/predicate"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// AccessPolicyUpdate is the builder for updating AccessPolicy entities.
type AccessPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *AccessPolicyMutation
}

// Where appends a list predicates to the AccessPolicyUpdate builder.
func (_u *AccessPolicyUpdate) Where(ps ...predicate.AccessPolicy) *AccessPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIPBurst10s sets the "ip_burst_10s" field.
func (_u *AccessPolicyUpdate) SetIPBurst10s(v int) *AccessPolicyUpdate {
	_u.mutation.ResetIPBurst10s()
	_u.mutation.SetIPBurst10s(v)
	return _u
}

// SetNillableIPBurst10s sets the "ip_burst_10s" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableIPBurst10s(v *int) *AccessPolicyUpdate {
	if v != nil {
		_u.SetIPBurst10s(*v)
	}
	return _u
}

// AddIPBurst10s adds value to the "ip_burst_10s" field.
func (_u *AccessPolicyUpdate) AddIPBurst10s(v int) *AccessPolicyUpdate {
	_u.mutation.AddIPBurst10s(v)
	return _u
}

// SetIPBurst60s sets the "ip_burst_60s" field.
func (_u *AccessPolicyUpdate) SetIPBurst60s(v int) *AccessPolicyUpdate {
	_u.mutation.ResetIPBurst60s()
	_u.mutation.SetIPBurst60s(v)
	return _u
}

// SetNillableIPBurst60s sets the "ip_burst_60s" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableIPBurst60s(v *int) *AccessPolicyUpdate {
	if v != nil {
		_u.SetIPBurst60s(*v)
	}
	return _u
}

// AddIPBurst60s adds value to the "ip_burst_60s" field.
func (_u *AccessPolicyUpdate) AddIPBurst60s(v int) *AccessPolicyUpdate {
	_u.mutation.AddIPBurst60s(v)
	return _u
}

// SetNameBurst10s sets the "name_burst_10s" field.
func (_u *AccessPolicyUpdate) SetNameBurst10s(v int) *AccessPolicyUpdate {
	_u.mutation.ResetNameBurst10s()
	_u.mutation.SetNameBurst10s(v)
	return _u
}

// SetNillableNameBurst10s sets the "name_burst_10s" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableNameBurst10s(v *int) *AccessPolicyUpdate {
	if v != nil {
		_u.SetNameBurst10s(*v)
	}
	return _u
}

// AddNameBurst10s adds value to the "name_burst_10s" field.
func (_u *AccessPolicyUpdate) AddNameBurst10s(v int) *AccessPolicyUpdate {
	_u.mutation.AddNameBurst10s(v)
	return _u
}

// SetNameBurst60s sets the "name_burst_60s" field.
func (_u *AccessPolicyUpdate) SetNameBurst60s(v int) *AccessPolicyUpdate {
	_u.mutation.ResetNameBurst60s()
	_u.mutation.SetNameBurst60s(v)
	return _u
}

// SetNillableNameBurst60s sets the "name_burst_60s" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableNameBurst60s(v *int) *AccessPolicyUpdate {
	if v != nil {
		_u.SetNameBurst60s(*v)
	}
	return _u
}

// AddNameBurst60s adds value to the "name_burst_60s" field.
func (_u *AccessPolicyUpdate) AddNameBurst60s(v int) *AccessPolicyUpdate {
	_u.mutation.AddNameBurst60s(v)
	return _u
}

// SetDenyFirst sets the "deny_first" field.
func (_u *AccessPolicyUpdate) SetDenyFirst(v bool) *AccessPolicyUpdate {
	_u.mutation.SetDenyFirst(v)
	return _u
}

// SetNillableDenyFirst sets the "deny_first" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableDenyFirst(v *bool) *AccessPolicyUpdate {
	if v != nil {
		_u.SetDenyFirst(*v)
	}
	return _u
}

// SetKickMessage sets the "kick_message" field.
func (_u *AccessPolicyUpdate) SetKickMessage(v string) *AccessPolicyUpdate {
	_u.mutation.SetKickMessage(v)
	return _u
}

// SetNillableKickMessage sets the "kick_message" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableKickMessage(v *string) *AccessPolicyUpdate {
	if v != nil {
		_u.SetKickMessage(*v)
	}
	return _u
}

// SetGeoMode sets the "geo_mode" field.
func (_u *AccessPolicyUpdate) SetGeoMode(v string) *AccessPolicyUpdate {
	_u.mutation.SetGeoMode(v)
	return _u
}

// SetNillableGeoMode sets the "geo_mode" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableGeoMode(v *string) *AccessPolicyUpdate {
	if v != nil {
		_u.SetGeoMode(*v)
	}
	return _u
}

// SetGeoList sets the "geo_list" field.
func (_u *AccessPolicyUpdate) SetGeoList(v []string) *AccessPolicyUpdate {
	_u.mutation.SetGeoList(v)
	return _u
}

// AppendGeoList appends value to the "geo_list" field.
func (_u *AccessPolicyUpdate) AppendGeoList(v []string) *AccessPolicyUpdate {
	_u.mutation.AppendGeoList(v)
	return _u
}

// ClearGeoList clears the value of the "geo_list" field.
func (_u *AccessPolicyUpdate) ClearGeoList() *AccessPolicyUpdate {
	_u.mutation.ClearGeoList()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AccessPolicyUpdate) SetCreatedAt(v time.Time) *AccessPolicyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableCreatedAt(v *time.Time) *AccessPolicyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessPolicyUpdate) SetUpdatedAt(v time.Time) *AccessPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *AccessPolicyUpdate) SetServerID(id int) *AccessPolicyUpdate {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *AccessPolicyUpdate) SetNillableServerID(id *int) *AccessPolicyUpdate {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *AccessPolicyUpdate) SetServer(v *Server) *AccessPolicyUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the AccessPolicyMutation object of the builder.
func (_u *AccessPolicyUpdate) Mutation() *AccessPolicyMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *AccessPolicyUpdate) ClearServer() *AccessPolicyUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accesspolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AccessPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(accesspolicy.Table, accesspolicy.Columns, sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IPBurst10s(); ok {
		_spec.SetField(accesspolicy.FieldIPBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIPBurst10s(); ok {
		_spec.AddField(accesspolicy.FieldIPBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPBurst60s(); ok {
		_spec.SetField(accesspolicy.FieldIPBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIPBurst60s(); ok {
		_spec.AddField(accesspolicy.FieldIPBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NameBurst10s(); ok {
		_spec.SetField(accesspolicy.FieldNameBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNameBurst10s(); ok {
		_spec.AddField(accesspolicy.FieldNameBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NameBurst60s(); ok {
		_spec.SetField(accesspolicy.FieldNameBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNameBurst60s(); ok {
		_spec.AddField(accesspolicy.FieldNameBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DenyFirst(); ok {
		_spec.SetField(accesspolicy.FieldDenyFirst, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KickMessage(); ok {
		_spec.SetField(accesspolicy.FieldKickMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.GeoMode(); ok {
		_spec.SetField(accesspolicy.FieldGeoMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GeoList(); ok {
		_spec.SetField(accesspolicy.FieldGeoList, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGeoList(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accesspolicy.FieldGeoList, value)
		})
	}
	if _u.mutation.GeoListCleared() {
		_spec.ClearField(accesspolicy.FieldGeoList, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(accesspolicy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accesspolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesspolicy.ServerTable,
			Columns: []string{accesspolicy.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesspolicy.ServerTable,
			Columns: []string{accesspolicy.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AccessPolicy
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesspolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessPolicyUpdateOne is the builder for updating a single AccessPolicy entity.
type AccessPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessPolicyMutation
}

// SetIPBurst10s sets the "ip_burst_10s" field.
func (_u *AccessPolicyUpdateOne) SetIPBurst10s(v int) *AccessPolicyUpdateOne {
	_u.mutation.ResetIPBurst10s()
	_u.mutation.SetIPBurst10s(v)
	return _u
}

// SetNillableIPBurst10s sets the "ip_burst_10s" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableIPBurst10s(v *int) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetIPBurst10s(*v)
	}
	return _u
}

// AddIPBurst10s adds value to the "ip_burst_10s" field.
func (_u *AccessPolicyUpdateOne) AddIPBurst10s(v int) *AccessPolicyUpdateOne {
	_u.mutation.AddIPBurst10s(v)
	return _u
}

// SetIPBurst60s sets the "ip_burst_60s" field.
func (_u *AccessPolicyUpdateOne) SetIPBurst60s(v int) *AccessPolicyUpdateOne {
	_u.mutation.ResetIPBurst60s()
	_u.mutation.SetIPBurst60s(v)
	return _u
}

// SetNillableIPBurst60s sets the "ip_burst_60s" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableIPBurst60s(v *int) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetIPBurst60s(*v)
	}
	return _u
}

// AddIPBurst60s adds value to the "ip_burst_60s" field.
func (_u *AccessPolicyUpdateOne) AddIPBurst60s(v int) *AccessPolicyUpdateOne {
	_u.mutation.AddIPBurst60s(v)
	return _u
}

// SetNameBurst10s sets the "name_burst_10s" field.
func (_u *AccessPolicyUpdateOne) SetNameBurst10s(v int) *AccessPolicyUpdateOne {
	_u.mutation.ResetNameBurst10s()
	_u.mutation.SetNameBurst10s(v)
	return _u
}

// SetNillableNameBurst10s sets the "name_burst_10s" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableNameBurst10s(v *int) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetNameBurst10s(*v)
	}
	return _u
}

// AddNameBurst10s adds value to the "name_burst_10s" field.
func (_u *AccessPolicyUpdateOne) AddNameBurst10s(v int) *AccessPolicyUpdateOne {
	_u.mutation.AddNameBurst10s(v)
	return _u
}

// SetNameBurst60s sets the "name_burst_60s" field.
func (_u *AccessPolicyUpdateOne) SetNameBurst60s(v int) *AccessPolicyUpdateOne {
	_u.mutation.ResetNameBurst60s()
	_u.mutation.SetNameBurst60s(v)
	return _u
}

// SetNillableNameBurst60s sets the "name_burst_60s" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableNameBurst60s(v *int) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetNameBurst60s(*v)
	}
	return _u
}

// AddNameBurst60s adds value to the "name_burst_60s" field.
func (_u *AccessPolicyUpdateOne) AddNameBurst60s(v int) *AccessPolicyUpdateOne {
	_u.mutation.AddNameBurst60s(v)
	return _u
}

// SetDenyFirst sets the "deny_first" field.
func (_u *AccessPolicyUpdateOne) SetDenyFirst(v bool) *AccessPolicyUpdateOne {
	_u.mutation.SetDenyFirst(v)
	return _u
}

// SetNillableDenyFirst sets the "deny_first" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableDenyFirst(v *bool) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetDenyFirst(*v)
	}
	return _u
}

// SetKickMessage sets the "kick_message" field.
func (_u *AccessPolicyUpdateOne) SetKickMessage(v string) *AccessPolicyUpdateOne {
	_u.mutation.SetKickMessage(v)
	return _u
}

// SetNillableKickMessage sets the "kick_message" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableKickMessage(v *string) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetKickMessage(*v)
	}
	return _u
}

// SetGeoMode sets the "geo_mode" field.
func (_u *AccessPolicyUpdateOne) SetGeoMode(v string) *AccessPolicyUpdateOne {
	_u.mutation.SetGeoMode(v)
	return _u
}

// SetNillableGeoMode sets the "geo_mode" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableGeoMode(v *string) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetGeoMode(*v)
	}
	return _u
}

// SetGeoList sets the "geo_list" field.
func (_u *AccessPolicyUpdateOne) SetGeoList(v []string) *AccessPolicyUpdateOne {
	_u.mutation.SetGeoList(v)
	return _u
}

// AppendGeoList appends value to the "geo_list" field.
func (_u *AccessPolicyUpdateOne) AppendGeoList(v []string) *AccessPolicyUpdateOne {
	_u.mutation.AppendGeoList(v)
	return _u
}

// ClearGeoList clears the value of the "geo_list" field.
func (_u *AccessPolicyUpdateOne) ClearGeoList() *AccessPolicyUpdateOne {
	_u.mutation.ClearGeoList()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AccessPolicyUpdateOne) SetCreatedAt(v time.Time) *AccessPolicyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableCreatedAt(v *time.Time) *AccessPolicyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessPolicyUpdateOne) SetUpdatedAt(v time.Time) *AccessPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *AccessPolicyUpdateOne) SetServerID(id int) *AccessPolicyUpdateOne {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *AccessPolicyUpdateOne) SetNillableServerID(id *int) *AccessPolicyUpdateOne {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *AccessPolicyUpdateOne) SetServer(v *Server) *AccessPolicyUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the AccessPolicyMutation object of the builder.
func (_u *AccessPolicyUpdateOne) Mutation() *AccessPolicyMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *AccessPolicyUpdateOne) ClearServer() *AccessPolicyUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the AccessPolicyUpdate builder.
func (_u *AccessPolicyUpdateOne) Where(ps ...predicate.AccessPolicy) *AccessPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessPolicyUpdateOne) Select(field string, fields ...string) *AccessPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessPolicy entity.
func (_u *AccessPolicyUpdateOne) Save(ctx context.Context) (*AccessPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessPolicyUpdateOne) SaveX(ctx context.Context) *AccessPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accesspolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AccessPolicyUpdateOne) sqlSave(ctx context.Context) (_node *AccessPolicy, err error) {
	_spec := sqlgraph.NewUpdateSpec(accesspolicy.Table, accesspolicy.Columns, sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesspolicy.FieldID)
		for _, f := range fields {
			if !accesspolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accesspolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IPBurst10s(); ok {
		_spec.SetField(accesspolicy.FieldIPBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIPBurst10s(); ok {
		_spec.AddField(accesspolicy.FieldIPBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPBurst60s(); ok {
		_spec.SetField(accesspolicy.FieldIPBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIPBurst60s(); ok {
		_spec.AddField(accesspolicy.FieldIPBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NameBurst10s(); ok {
		_spec.SetField(accesspolicy.FieldNameBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNameBurst10s(); ok {
		_spec.AddField(accesspolicy.FieldNameBurst10s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NameBurst60s(); ok {
		_spec.SetField(accesspolicy.FieldNameBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNameBurst60s(); ok {
		_spec.AddField(accesspolicy.FieldNameBurst60s, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DenyFirst(); ok {
		_spec.SetField(accesspolicy.FieldDenyFirst, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KickMessage(); ok {
		_spec.SetField(accesspolicy.FieldKickMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.GeoMode(); ok {
		_spec.SetField(accesspolicy.FieldGeoMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GeoList(); ok {
		_spec.SetField(accesspolicy.FieldGeoList, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGeoList(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accesspolicy.FieldGeoList, value)
		})
	}
	if _u.mutation.GeoListCleared() {
		_spec.ClearField(accesspolicy.FieldGeoList, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(accesspolicy.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accesspolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesspolicy.ServerTable,
			Columns: []string{accesspolicy.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesspolicy.ServerTable,
			Columns: []string{accesspolicy.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AccessPolicy
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &AccessPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesspolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
