// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"mcproxy/internal/ent/accesspolicy"
	"mcproxy/internal/ent/server"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AccessPolicy is the model entity for the AccessPolicy schema.
type AccessPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IPBurst10s holds the value of the "ip_burst_10s" field.
	IPBurst10s int `json:"ip_burst_10s,omitempty"`
	// IPBurst60s holds the value of the "ip_burst_60s" field.
	IPBurst60s int `json:"ip_burst_60s,omitempty"`
	// NameBurst10s holds the value of the "name_burst_10s" field.
	NameBurst10s int `json:"name_burst_10s,omitempty"`
	// NameBurst60s holds the value of the "name_burst_60s" field.
	NameBurst60s int `json:"name_burst_60s,omitempty"`
	// DenyFirst holds the value of the "deny_first" field.
	DenyFirst bool `json:"deny_first,omitempty"`
	// KickMessage holds the value of the "kick_message" field.
	KickMessage string `json:"kick_message,omitempty"`
	// GeoMode holds the value of the "geo_mode" field.
	GeoMode string `json:"geo_mode,omitempty"`
	// GeoList holds the value of the "geo_list" field.
	GeoList []string `json:"geo_list,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessPolicyQuery when eager-loading is set.
	Edges           AccessPolicyEdges `json:"edges"`
	server_policies *int
	selectValues    sql.SelectValues
}

// AccessPolicyEdges holds the relations/edges for other nodes in the graph.
type AccessPolicyEdges struct {
	// Server holds the value of the server edge.
	Server *Server `json:"server,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServerOrErr returns the Server value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccessPolicyEdges) ServerOrErr() (*Server, error) {
	if e.Server != nil {
		return e.Server, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: server.Label}
	}
	return nil, &NotLoadedError{edge: "server"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesspolicy.FieldGeoList:
			values[i] = new([]byte)
		case accesspolicy.FieldDenyFirst:
			values[i] = new(sql.NullBool)
		case accesspolicy.FieldID, accesspolicy.FieldIPBurst10s, accesspolicy.FieldIPBurst60s, accesspolicy.FieldNameBurst10s, accesspolicy.FieldNameBurst60s:
			values[i] = new(sql.NullInt64)
		case accesspolicy.FieldKickMessage, accesspolicy.FieldGeoMode:
			values[i] = new(sql.NullString)
		case accesspolicy.FieldCreatedAt, accesspolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case accesspolicy.ForeignKeys[0]: // server_policies
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessPolicy fields.
func (_m *AccessPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesspolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case accesspolicy.FieldIPBurst10s:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ip_burst_10s", values[i])
			} else if value.Valid {
				_m.IPBurst10s = int(value.Int64)
			}
		case accesspolicy.FieldIPBurst60s:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ip_burst_60s", values[i])
			} else if value.Valid {
				_m.IPBurst60s = int(value.Int64)
			}
		case accesspolicy.FieldNameBurst10s:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field name_burst_10s", values[i])
			} else if value.Valid {
				_m.NameBurst10s = int(value.Int64)
			}
		case accesspolicy.FieldNameBurst60s:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field name_burst_60s", values[i])
			} else if value.Valid {
				_m.NameBurst60s = int(value.Int64)
			}
		case accesspolicy.FieldDenyFirst:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deny_first", values[i])
			} else if value.Valid {
				_m.DenyFirst = value.Bool
			}
		case accesspolicy.FieldKickMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kick_message", values[i])
			} else if value.Valid {
				_m.KickMessage = value.String
			}
		case accesspolicy.FieldGeoMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field geo_mode", values[i])
			} else if value.Valid {
				_m.GeoMode = value.String
			}
		case accesspolicy.FieldGeoList:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field geo_list", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GeoList); err != nil {
					return fmt.Errorf("unmarshal field geo_list: %w", err)
				}
			}
		case accesspolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accesspolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accesspolicy.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field server_policies", value)
			} else if value.Valid {
				_m.server_policies = new(int)
				*_m.server_policies = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *AccessPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryServer queries the "server" edge of the AccessPolicy entity.
func (_m *AccessPolicy) QueryServer() *ServerQuery {
	return NewAccessPolicyClient(_m.config).QueryServer(_m)
}

// Update returns a builder for updating this AccessPolicy.
// Note that you need to call AccessPolicy.Unwrap() before calling this method if this AccessPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessPolicy) Update() *AccessPolicyUpdateOne {
	return NewAccessPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessPolicy) Unwrap() *AccessPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("AccessPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ip_burst_10s=")
	builder.WriteString(fmt.Sprintf("%v", _m.IPBurst10s))
	builder.WriteString(", ")
	builder.WriteString("ip_burst_60s=")
	builder.WriteString(fmt.Sprintf("%v", _m.IPBurst60s))
	builder.WriteString(", ")
	builder.WriteString("name_burst_10s=")
	builder.WriteString(fmt.Sprintf("%v", _m.NameBurst10s))
	builder.WriteString(", ")
	builder.WriteString("name_burst_60s=")
	builder.WriteString(fmt.Sprintf("%v", _m.NameBurst60s))
	builder.WriteString(", ")
	builder.WriteString("deny_first=")
	builder.WriteString(fmt.Sprintf("%v", _m.DenyFirst))
	builder.WriteString(", ")
	builder.WriteString("kick_message=")
	builder.WriteString(_m.KickMessage)
	builder.WriteString(", ")
	builder.WriteString("geo_mode=")
	builder.WriteString(_m.GeoMode)
	builder.WriteString(", ")
	builder.WriteString("geo_list=")
	builder.WriteString(fmt.Sprintf("%v", _m.GeoList))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccessPolicies is a parsable slice of AccessPolicy.
type AccessPolicies []*AccessPolicy
