// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/audit"
	"mcproxy/internal/ent/internal"
	"mcproxy/internal/ent/predicate"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditUpdate is the builder for updating Audit entities.
type AuditUpdate struct {
	config
	hooks    []Hook
	mutation *AuditMutation
}

// Where appends a list predicates to the AuditUpdate builder.
func (_u *AuditUpdate) Where(ps ...predicate.Audit) *AuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEvent sets the "event" field.
func (_u *AuditUpdate) SetEvent(v string) *AuditUpdate {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableEvent(v *string) *AuditUpdate {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *AuditUpdate) SetActor(v string) *AuditUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableActor(v *string) *AuditUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *AuditUpdate) ClearActor() *AuditUpdate {
	_u.mutation.ClearActor()
	return _u
}

// SetDetails sets the "details" field.
func (_u *AuditUpdate) SetDetails(v map[string]interface{}) *AuditUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *AuditUpdate) ClearDetails() *AuditUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditUpdate) SetCreatedAt(v time.Time) *AuditUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableCreatedAt(v *time.Time) *AuditUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *AuditUpdate) SetServerID(id int) *AuditUpdate {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *AuditUpdate) SetNillableServerID(id *int) *AuditUpdate {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *AuditUpdate) SetServer(v *Server) *AuditUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the AuditMutation object of the builder.
func (_u *AuditUpdate) Mutation() *AuditMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *AuditUpdate) ClearServer() *AuditUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditUpdate) check() error {
	if v, ok := _u.mutation.Event(); ok {
		if err := audit.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "Audit.event": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(audit.Table, audit.Columns, sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(audit.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(audit.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(audit.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(audit.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(audit.FieldDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(audit.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   audit.ServerTable,
			Columns: []string{audit.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   audit.ServerTable,
			Columns: []string{audit.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Audit
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditUpdateOne is the builder for updating a single Audit entity.
type AuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditMutation
}

// SetEvent sets the "event" field.
func (_u *AuditUpdateOne) SetEvent(v string) *AuditUpdateOne {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableEvent(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *AuditUpdateOne) SetActor(v string) *AuditUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableActor(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *AuditUpdateOne) ClearActor() *AuditUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// SetDetails sets the "details" field.
func (_u *AuditUpdateOne) SetDetails(v map[string]interface{}) *AuditUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *AuditUpdateOne) ClearDetails() *AuditUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditUpdateOne) SetCreatedAt(v time.Time) *AuditUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableCreatedAt(v *time.Time) *AuditUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *AuditUpdateOne) SetServerID(id int) *AuditUpdateOne {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableServerID(id *int) *AuditUpdateOne {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *AuditUpdateOne) SetServer(v *Server) *AuditUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the AuditMutation object of the builder.
func (_u *AuditUpdateOne) Mutation() *AuditMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *AuditUpdateOne) ClearServer() *AuditUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the AuditUpdate builder.
func (_u *AuditUpdateOne) Where(ps ...predicate.Audit) *AuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditUpdateOne) Select(field string, fields ...string) *AuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Audit entity.
func (_u *AuditUpdateOne) Save(ctx context.Context) (*Audit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditUpdateOne) SaveX(ctx context.Context) *Audit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditUpdateOne) check() error {
	if v, ok := _u.mutation.Event(); ok {
		if err := audit.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "Audit.event": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditUpdateOne) sqlSave(ctx context.Context) (_node *Audit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(audit.Table, audit.Columns, sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Audit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audit.FieldID)
		for _, f := range fields {
			if !audit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != audit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(audit.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(audit.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(audit.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(audit.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(audit.FieldDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(audit.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   audit.ServerTable,
			Columns: []string{audit.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   audit.ServerTable,
			Columns: []string{audit.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Audit
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Audit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
