// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/audit"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditCreate is the builder for creating a Audit entity.
type AuditCreate struct {
	config
	mutation *AuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEvent sets the "event" field.
func (_c *AuditCreate) SetEvent(v string) *AuditCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *AuditCreate) SetActor(v string) *AuditCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_c *AuditCreate) SetNillableActor(v *string) *AuditCreate {
	if v != nil {
		_c.SetActor(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *AuditCreate) SetDetails(v map[string]interface{}) *AuditCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditCreate) SetCreatedAt(v time.Time) *AuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditCreate) SetNillableCreatedAt(v *time.Time) *AuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_c *AuditCreate) SetServerID(id int) *AuditCreate {
	_c.mutation.SetServerID(id)
	return _c
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_c *AuditCreate) SetNillableServerID(id *int) *AuditCreate {
	if id != nil {
		_c = _c.SetServerID(*id)
	}
	return _c
}

// SetServer sets the "server" edge to the Server entity.
func (_c *AuditCreate) SetServer(v *Server) *AuditCreate {
	return _c.SetServerID(v.ID)
}

// Mutation returns the AuditMutation object of the builder.
func (_c *AuditCreate) Mutation() *AuditMutation {
	return _c.mutation
}

// Save creates the Audit in the database.
func (_c *AuditCreate) Save(ctx context.Context) (*Audit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditCreate) SaveX(ctx context.Context) *Audit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditCreate) defaults() {
	if _, ok := _c.mutation.Details(); !ok {
		v := audit.DefaultDetails
		_c.mutation.SetDetails(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := audit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditCreate) check() error {
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "Audit.event"`)}
	}
	if v, ok := _c.mutation.Event(); ok {
		if err := audit.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "Audit.event": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Audit.created_at"`)}
	}
	return nil
}

func (_c *AuditCreate) sqlSave(ctx context.Context) (*Audit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditCreate) createSpec() (*Audit, *sqlgraph.CreateSpec) {
	var (
		_node = &Audit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(audit.Table, sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Audit
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(audit.FieldEvent, field.TypeString, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(audit.FieldActor, field.TypeString, value)
		_node.Actor = &value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(audit.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(audit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   audit.ServerTable,
			Columns: []string{audit.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.server_audits = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Audit.Create().
//		SetEvent(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditUpsert) {
//			SetEvent(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditCreate) OnConflict(opts ...sql.ConflictOption) *AuditUpsertOne {
	_c.conflict = opts
	return &AuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Audit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditCreate) OnConflictColumns(columns ...string) *AuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditUpsertOne{
		create: _c,
	}
}

type (
	// AuditUpsertOne is the builder for "upsert"-ing
	//  one Audit node.
	AuditUpsertOne struct {
		create *AuditCreate
	}

	// AuditUpsert is the "OnConflict" setter.
	AuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetEvent sets the "event" field.
func (u *AuditUpsert) SetEvent(v string) *AuditUpsert {
	u.Set(audit.FieldEvent, v)
	return u
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *AuditUpsert) UpdateEvent() *AuditUpsert {
	u.SetExcluded(audit.FieldEvent)
	return u
}

// SetActor sets the "actor" field.
func (u *AuditUpsert) SetActor(v string) *AuditUpsert {
	u.Set(audit.FieldActor, v)
	return u
}

// UpdateActor sets the "actor" field to the value that was provided on create.
func (u *AuditUpsert) UpdateActor() *AuditUpsert {
	u.SetExcluded(audit.FieldActor)
	return u
}

// ClearActor clears the value of the "actor" field.
func (u *AuditUpsert) ClearActor() *AuditUpsert {
	u.SetNull(audit.FieldActor)
	return u
}

// SetDetails sets the "details" field.
func (u *AuditUpsert) SetDetails(v map[string]interface{}) *AuditUpsert {
	u.Set(audit.FieldDetails, v)
	return u
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *AuditUpsert) UpdateDetails() *AuditUpsert {
	u.SetExcluded(audit.FieldDetails)
	return u
}

// ClearDetails clears the value of the "details" field.
func (u *AuditUpsert) ClearDetails() *AuditUpsert {
	u.SetNull(audit.FieldDetails)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AuditUpsert) SetCreatedAt(v time.Time) *AuditUpsert {
	u.Set(audit.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AuditUpsert) UpdateCreatedAt() *AuditUpsert {
	u.SetExcluded(audit.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Audit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuditUpsertOne) UpdateNewValues() *AuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Audit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditUpsertOne) Ignore() *AuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditUpsertOne) DoNothing() *AuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditCreate.OnConflict
// documentation for more info.
func (u *AuditUpsertOne) Update(set func(*AuditUpsert)) *AuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetEvent sets the "event" field.
func (u *AuditUpsertOne) SetEvent(v string) *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *AuditUpsertOne) UpdateEvent() *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateEvent()
	})
}

// SetActor sets the "actor" field.
func (u *AuditUpsertOne) SetActor(v string) *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.SetActor(v)
	})
}

// UpdateActor sets the "actor" field to the value that was provided on create.
func (u *AuditUpsertOne) UpdateActor() *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateActor()
	})
}

// ClearActor clears the value of the "actor" field.
func (u *AuditUpsertOne) ClearActor() *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.ClearActor()
	})
}

// SetDetails sets the "details" field.
func (u *AuditUpsertOne) SetDetails(v map[string]interface{}) *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.SetDetails(v)
	})
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *AuditUpsertOne) UpdateDetails() *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateDetails()
	})
}

// ClearDetails clears the value of the "details" field.
func (u *AuditUpsertOne) ClearDetails() *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.ClearDetails()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AuditUpsertOne) SetCreatedAt(v time.Time) *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AuditUpsertOne) UpdateCreatedAt() *AuditUpsertOne {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *AuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditCreateBulk is the builder for creating many Audit entities in bulk.
type AuditCreateBulk struct {
	config
	err      error
	builders []*AuditCreate
	conflict []sql.ConflictOption
}

// Save creates the Audit entities in the database.
func (_c *AuditCreateBulk) Save(ctx context.Context) ([]*Audit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Audit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditCreateBulk) SaveX(ctx context.Context) []*Audit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Audit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditUpsert) {
//			SetEvent(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditUpsertBulk {
	_c.conflict = opts
	return &AuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Audit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditCreateBulk) OnConflictColumns(columns ...string) *AuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditUpsertBulk{
		create: _c,
	}
}

// AuditUpsertBulk is the builder for "upsert"-ing
// a bulk of Audit nodes.
type AuditUpsertBulk struct {
	create *AuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Audit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuditUpsertBulk) UpdateNewValues() *AuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Audit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditUpsertBulk) Ignore() *AuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditUpsertBulk) DoNothing() *AuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditCreateBulk.OnConflict
// documentation for more info.
func (u *AuditUpsertBulk) Update(set func(*AuditUpsert)) *AuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetEvent sets the "event" field.
func (u *AuditUpsertBulk) SetEvent(v string) *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *AuditUpsertBulk) UpdateEvent() *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateEvent()
	})
}

// SetActor sets the "actor" field.
func (u *AuditUpsertBulk) SetActor(v string) *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.SetActor(v)
	})
}

// UpdateActor sets the "actor" field to the value that was provided on create.
func (u *AuditUpsertBulk) UpdateActor() *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateActor()
	})
}

// ClearActor clears the value of the "actor" field.
func (u *AuditUpsertBulk) ClearActor() *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.ClearActor()
	})
}

// SetDetails sets the "details" field.
func (u *AuditUpsertBulk) SetDetails(v map[string]interface{}) *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.SetDetails(v)
	})
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *AuditUpsertBulk) UpdateDetails() *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateDetails()
	})
}

// ClearDetails clears the value of the "details" field.
func (u *AuditUpsertBulk) ClearDetails() *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.ClearDetails()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AuditUpsertBulk) SetCreatedAt(v time.Time) *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AuditUpsertBulk) UpdateCreatedAt() *AuditUpsertBulk {
	return u.Update(func(s *AuditUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *AuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
