// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/counter"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CounterCreate is the builder for creating a Counter entity.
type CounterCreate struct {
	config
	mutation *CounterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *CounterCreate) SetKind(v string) *CounterCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *CounterCreate) SetKey(v string) *CounterCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetWindowSec sets the "window_sec" field.
func (_c *CounterCreate) SetWindowSec(v int) *CounterCreate {
	_c.mutation.SetWindowSec(v)
	return _c
}

// SetCount sets the "count" field.
func (_c *CounterCreate) SetCount(v int) *CounterCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_c *CounterCreate) SetNillableCount(v *int) *CounterCreate {
	if v != nil {
		_c.SetCount(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *CounterCreate) SetLastSeen(v time.Time) *CounterCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *CounterCreate) SetNillableLastSeen(v *time.Time) *CounterCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CounterCreate) SetCreatedAt(v time.Time) *CounterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CounterCreate) SetNillableCreatedAt(v *time.Time) *CounterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CounterCreate) SetUpdatedAt(v time.Time) *CounterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CounterCreate) SetNillableUpdatedAt(v *time.Time) *CounterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_c *CounterCreate) SetServerID(id int) *CounterCreate {
	_c.mutation.SetServerID(id)
	return _c
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_c *CounterCreate) SetNillableServerID(id *int) *CounterCreate {
	if id != nil {
		_c = _c.SetServerID(*id)
	}
	return _c
}

// SetServer sets the "server" edge to the Server entity.
func (_c *CounterCreate) SetServer(v *Server) *CounterCreate {
	return _c.SetServerID(v.ID)
}

// Mutation returns the CounterMutation object of the builder.
func (_c *CounterCreate) Mutation() *CounterMutation {
	return _c.mutation
}

// Save creates the Counter in the database.
func (_c *CounterCreate) Save(ctx context.Context) (*Counter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CounterCreate) SaveX(ctx context.Context) *Counter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CounterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CounterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CounterCreate) defaults() {
	if _, ok := _c.mutation.Count(); !ok {
		v := counter.DefaultCount
		_c.mutation.SetCount(v)
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		v := counter.DefaultLastSeen()
		_c.mutation.SetLastSeen(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := counter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := counter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CounterCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Counter.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := counter.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Counter.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Counter.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := counter.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Counter.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WindowSec(); !ok {
		return &ValidationError{Name: "window_sec", err: errors.New(`ent: missing required field "Counter.window_sec"`)}
	}
	if v, ok := _c.mutation.WindowSec(); ok {
		if err := counter.WindowSecValidator(v); err != nil {
			return &ValidationError{Name: "window_sec", err: fmt.Errorf(`ent: validator failed for field "Counter.window_sec": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Counter.count"`)}
	}
	if v, ok := _c.mutation.Count(); ok {
		if err := counter.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Counter.count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		return &ValidationError{Name: "last_seen", err: errors.New(`ent: missing required field "Counter.last_seen"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Counter.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Counter.updated_at"`)}
	}
	return nil
}

func (_c *CounterCreate) sqlSave(ctx context.Context) (*Counter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CounterCreate) createSpec() (*Counter, *sqlgraph.CreateSpec) {
	var (
		_node = &Counter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(counter.Table, sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Counter
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(counter.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(counter.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.WindowSec(); ok {
		_spec.SetField(counter.FieldWindowSec, field.TypeInt, value)
		_node.WindowSec = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(counter.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(counter.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(counter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(counter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   counter.ServerTable,
			Columns: []string{counter.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.server_counters = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Counter.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CounterUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *CounterCreate) OnConflict(opts ...sql.ConflictOption) *CounterUpsertOne {
	_c.conflict = opts
	return &CounterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CounterCreate) OnConflictColumns(columns ...string) *CounterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CounterUpsertOne{
		create: _c,
	}
}

type (
	// CounterUpsertOne is the builder for "upsert"-ing
	//  one Counter node.
	CounterUpsertOne struct {
		create *CounterCreate
	}

	// CounterUpsert is the "OnConflict" setter.
	CounterUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *CounterUpsert) SetKind(v string) *CounterUpsert {
	u.Set(counter.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CounterUpsert) UpdateKind() *CounterUpsert {
	u.SetExcluded(counter.FieldKind)
	return u
}

// SetKey sets the "key" field.
func (u *CounterUpsert) SetKey(v string) *CounterUpsert {
	u.Set(counter.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CounterUpsert) UpdateKey() *CounterUpsert {
	u.SetExcluded(counter.FieldKey)
	return u
}

// SetWindowSec sets the "window_sec" field.
func (u *CounterUpsert) SetWindowSec(v int) *CounterUpsert {
	u.Set(counter.FieldWindowSec, v)
	return u
}

// UpdateWindowSec sets the "window_sec" field to the value that was provided on create.
func (u *CounterUpsert) UpdateWindowSec() *CounterUpsert {
	u.SetExcluded(counter.FieldWindowSec)
	return u
}

// AddWindowSec adds v to the "window_sec" field.
func (u *CounterUpsert) AddWindowSec(v int) *CounterUpsert {
	u.Add(counter.FieldWindowSec, v)
	return u
}

// SetCount sets the "count" field.
func (u *CounterUpsert) SetCount(v int) *CounterUpsert {
	u.Set(counter.FieldCount, v)
	return u
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *CounterUpsert) UpdateCount() *CounterUpsert {
	u.SetExcluded(counter.FieldCount)
	return u
}

// AddCount adds v to the "count" field.
func (u *CounterUpsert) AddCount(v int) *CounterUpsert {
	u.Add(counter.FieldCount, v)
	return u
}

// SetLastSeen sets the "last_seen" field.
func (u *CounterUpsert) SetLastSeen(v time.Time) *CounterUpsert {
	u.Set(counter.FieldLastSeen, v)
	return u
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *CounterUpsert) UpdateLastSeen() *CounterUpsert {
	u.SetExcluded(counter.FieldLastSeen)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CounterUpsert) SetCreatedAt(v time.Time) *CounterUpsert {
	u.Set(counter.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CounterUpsert) UpdateCreatedAt() *CounterUpsert {
	u.SetExcluded(counter.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CounterUpsert) SetUpdatedAt(v time.Time) *CounterUpsert {
	u.Set(counter.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CounterUpsert) UpdateUpdatedAt() *CounterUpsert {
	u.SetExcluded(counter.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CounterUpsertOne) UpdateNewValues() *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Counter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CounterUpsertOne) Ignore() *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CounterUpsertOne) DoNothing() *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CounterCreate.OnConflict
// documentation for more info.
func (u *CounterUpsertOne) Update(set func(*CounterUpsert)) *CounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CounterUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *CounterUpsertOne) SetKind(v string) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateKind() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateKind()
	})
}

// SetKey sets the "key" field.
func (u *CounterUpsertOne) SetKey(v string) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateKey() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateKey()
	})
}

// SetWindowSec sets the "window_sec" field.
func (u *CounterUpsertOne) SetWindowSec(v int) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetWindowSec(v)
	})
}

// AddWindowSec adds v to the "window_sec" field.
func (u *CounterUpsertOne) AddWindowSec(v int) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.AddWindowSec(v)
	})
}

// UpdateWindowSec sets the "window_sec" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateWindowSec() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateWindowSec()
	})
}

// SetCount sets the "count" field.
func (u *CounterUpsertOne) SetCount(v int) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetCount(v)
	})
}

// AddCount adds v to the "count" field.
func (u *CounterUpsertOne) AddCount(v int) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.AddCount(v)
	})
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateCount() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateCount()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *CounterUpsertOne) SetLastSeen(v time.Time) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateLastSeen() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateLastSeen()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CounterUpsertOne) SetCreatedAt(v time.Time) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateCreatedAt() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CounterUpsertOne) SetUpdatedAt(v time.Time) *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CounterUpsertOne) UpdateUpdatedAt() *CounterUpsertOne {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CounterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CounterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CounterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CounterUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CounterUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CounterCreateBulk is the builder for creating many Counter entities in bulk.
type CounterCreateBulk struct {
	config
	err      error
	builders []*CounterCreate
	conflict []sql.ConflictOption
}

// Save creates the Counter entities in the database.
func (_c *CounterCreateBulk) Save(ctx context.Context) ([]*Counter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Counter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CounterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CounterCreateBulk) SaveX(ctx context.Context) []*Counter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CounterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CounterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Counter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CounterUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *CounterCreateBulk) OnConflict(opts ...sql.ConflictOption) *CounterUpsertBulk {
	_c.conflict = opts
	return &CounterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CounterCreateBulk) OnConflictColumns(columns ...string) *CounterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CounterUpsertBulk{
		create: _c,
	}
}

// CounterUpsertBulk is the builder for "upsert"-ing
// a bulk of Counter nodes.
type CounterUpsertBulk struct {
	create *CounterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CounterUpsertBulk) UpdateNewValues() *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Counter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CounterUpsertBulk) Ignore() *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CounterUpsertBulk) DoNothing() *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CounterCreateBulk.OnConflict
// documentation for more info.
func (u *CounterUpsertBulk) Update(set func(*CounterUpsert)) *CounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CounterUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *CounterUpsertBulk) SetKind(v string) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateKind() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateKind()
	})
}

// SetKey sets the "key" field.
func (u *CounterUpsertBulk) SetKey(v string) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateKey() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateKey()
	})
}

// SetWindowSec sets the "window_sec" field.
func (u *CounterUpsertBulk) SetWindowSec(v int) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetWindowSec(v)
	})
}

// AddWindowSec adds v to the "window_sec" field.
func (u *CounterUpsertBulk) AddWindowSec(v int) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.AddWindowSec(v)
	})
}

// UpdateWindowSec sets the "window_sec" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateWindowSec() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateWindowSec()
	})
}

// SetCount sets the "count" field.
func (u *CounterUpsertBulk) SetCount(v int) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetCount(v)
	})
}

// AddCount adds v to the "count" field.
func (u *CounterUpsertBulk) AddCount(v int) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.AddCount(v)
	})
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateCount() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateCount()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *CounterUpsertBulk) SetLastSeen(v time.Time) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateLastSeen() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateLastSeen()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CounterUpsertBulk) SetCreatedAt(v time.Time) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateCreatedAt() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CounterUpsertBulk) SetUpdatedAt(v time.Time) *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CounterUpsertBulk) UpdateUpdatedAt() *CounterUpsertBulk {
	return u.Update(func(s *CounterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CounterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CounterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CounterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CounterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
