// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/counter"
	"mcproxy/internal/ent/internal"
	"mcproxy/internal/ent/predicate"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CounterUpdate is the builder for updating Counter entities.
type CounterUpdate struct {
	config
	hooks    []Hook
	mutation *CounterMutation
}

// Where appends a list predicates to the CounterUpdate builder.
func (_u *CounterUpdate) Where(ps ...predicate.Counter) *CounterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *CounterUpdate) SetKind(v string) *CounterUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CounterUpdate) SetNillableKind(v *string) *CounterUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *CounterUpdate) SetKey(v string) *CounterUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *CounterUpdate) SetNillableKey(v *string) *CounterUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetWindowSec sets the "window_sec" field.
func (_u *CounterUpdate) SetWindowSec(v int) *CounterUpdate {
	_u.mutation.ResetWindowSec()
	_u.mutation.SetWindowSec(v)
	return _u
}

// SetNillableWindowSec sets the "window_sec" field if the given value is not nil.
func (_u *CounterUpdate) SetNillableWindowSec(v *int) *CounterUpdate {
	if v != nil {
		_u.SetWindowSec(*v)
	}
	return _u
}

// AddWindowSec adds value to the "window_sec" field.
func (_u *CounterUpdate) AddWindowSec(v int) *CounterUpdate {
	_u.mutation.AddWindowSec(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *CounterUpdate) SetCount(v int) *CounterUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *CounterUpdate) SetNillableCount(v *int) *CounterUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *CounterUpdate) AddCount(v int) *CounterUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *CounterUpdate) SetLastSeen(v time.Time) *CounterUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *CounterUpdate) SetNillableLastSeen(v *time.Time) *CounterUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CounterUpdate) SetCreatedAt(v time.Time) *CounterUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CounterUpdate) SetNillableCreatedAt(v *time.Time) *CounterUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CounterUpdate) SetUpdatedAt(v time.Time) *CounterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *CounterUpdate) SetServerID(id int) *CounterUpdate {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *CounterUpdate) SetNillableServerID(id *int) *CounterUpdate {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *CounterUpdate) SetServer(v *Server) *CounterUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the CounterMutation object of the builder.
func (_u *CounterUpdate) Mutation() *CounterMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *CounterUpdate) ClearServer() *CounterUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CounterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CounterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CounterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CounterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CounterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := counter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CounterUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := counter.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Counter.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := counter.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Counter.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WindowSec(); ok {
		if err := counter.WindowSecValidator(v); err != nil {
			return &ValidationError{Name: "window_sec", err: fmt.Errorf(`ent: validator failed for field "Counter.window_sec": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Count(); ok {
		if err := counter.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Counter.count": %w`, err)}
		}
	}
	return nil
}

func (_u *CounterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(counter.Table, counter.Columns, sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(counter.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(counter.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowSec(); ok {
		_spec.SetField(counter.FieldWindowSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWindowSec(); ok {
		_spec.AddField(counter.FieldWindowSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(counter.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(counter.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(counter.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(counter.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(counter.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   counter.ServerTable,
			Columns: []string{counter.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   counter.ServerTable,
			Columns: []string{counter.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Counter
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{counter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CounterUpdateOne is the builder for updating a single Counter entity.
type CounterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CounterMutation
}

// SetKind sets the "kind" field.
func (_u *CounterUpdateOne) SetKind(v string) *CounterUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableKind(v *string) *CounterUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *CounterUpdateOne) SetKey(v string) *CounterUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableKey(v *string) *CounterUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetWindowSec sets the "window_sec" field.
func (_u *CounterUpdateOne) SetWindowSec(v int) *CounterUpdateOne {
	_u.mutation.ResetWindowSec()
	_u.mutation.SetWindowSec(v)
	return _u
}

// SetNillableWindowSec sets the "window_sec" field if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableWindowSec(v *int) *CounterUpdateOne {
	if v != nil {
		_u.SetWindowSec(*v)
	}
	return _u
}

// AddWindowSec adds value to the "window_sec" field.
func (_u *CounterUpdateOne) AddWindowSec(v int) *CounterUpdateOne {
	_u.mutation.AddWindowSec(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *CounterUpdateOne) SetCount(v int) *CounterUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableCount(v *int) *CounterUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *CounterUpdateOne) AddCount(v int) *CounterUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *CounterUpdateOne) SetLastSeen(v time.Time) *CounterUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableLastSeen(v *time.Time) *CounterUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CounterUpdateOne) SetCreatedAt(v time.Time) *CounterUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableCreatedAt(v *time.Time) *CounterUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CounterUpdateOne) SetUpdatedAt(v time.Time) *CounterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *CounterUpdateOne) SetServerID(id int) *CounterUpdateOne {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *CounterUpdateOne) SetNillableServerID(id *int) *CounterUpdateOne {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *CounterUpdateOne) SetServer(v *Server) *CounterUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the CounterMutation object of the builder.
func (_u *CounterUpdateOne) Mutation() *CounterMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *CounterUpdateOne) ClearServer() *CounterUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the CounterUpdate builder.
func (_u *CounterUpdateOne) Where(ps ...predicate.Counter) *CounterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CounterUpdateOne) Select(field string, fields ...string) *CounterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Counter entity.
func (_u *CounterUpdateOne) Save(ctx context.Context) (*Counter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CounterUpdateOne) SaveX(ctx context.Context) *Counter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CounterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CounterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CounterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := counter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CounterUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := counter.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Counter.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := counter.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Counter.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WindowSec(); ok {
		if err := counter.WindowSecValidator(v); err != nil {
			return &ValidationError{Name: "window_sec", err: fmt.Errorf(`ent: validator failed for field "Counter.window_sec": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Count(); ok {
		if err := counter.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Counter.count": %w`, err)}
		}
	}
	return nil
}

func (_u *CounterUpdateOne) sqlSave(ctx context.Context) (_node *Counter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(counter.Table, counter.Columns, sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Counter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, counter.FieldID)
		for _, f := range fields {
			if !counter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != counter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(counter.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(counter.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowSec(); ok {
		_spec.SetField(counter.FieldWindowSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWindowSec(); ok {
		_spec.AddField(counter.FieldWindowSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(counter.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(counter.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(counter.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(counter.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(counter.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   counter.ServerTable,
			Columns: []string{counter.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   counter.ServerTable,
			Columns: []string{counter.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Counter
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Counter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{counter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
