// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mcproxy/internal/ent/counter"
	"mcproxy/internal/ent/server"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Counter is the model entity for the Counter schema.
type Counter struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// WindowSec holds the value of the "window_sec" field.
	WindowSec int `json:"window_sec,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen time.Time `json:"last_seen,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CounterQuery when eager-loading is set.
	Edges           CounterEdges `json:"edges"`
	server_counters *int
	selectValues    sql.SelectValues
}

// CounterEdges holds the relations/edges for other nodes in the graph.
type CounterEdges struct {
	// Server holds the value of the server edge.
	Server *Server `json:"server,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServerOrErr returns the Server value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CounterEdges) ServerOrErr() (*Server, error) {
	if e.Server != nil {
		return e.Server, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: server.Label}
	}
	return nil, &NotLoadedError{edge: "server"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Counter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case counter.FieldID, counter.FieldWindowSec, counter.FieldCount:
			values[i] = new(sql.NullInt64)
		case counter.FieldKind, counter.FieldKey:
			values[i] = new(sql.NullString)
		case counter.FieldLastSeen, counter.FieldCreatedAt, counter.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case counter.ForeignKeys[0]: // server_counters
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Counter fields.
func (_m *Counter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case counter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case counter.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case counter.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case counter.FieldWindowSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field window_sec", values[i])
			} else if value.Valid {
				_m.WindowSec = int(value.Int64)
			}
		case counter.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case counter.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = value.Time
			}
		case counter.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case counter.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case counter.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field server_counters", value)
			} else if value.Valid {
				_m.server_counters = new(int)
				*_m.server_counters = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Counter.
// This includes values selected through modifiers, order, etc.
func (_m *Counter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryServer queries the "server" edge of the Counter entity.
func (_m *Counter) QueryServer() *ServerQuery {
	return NewCounterClient(_m.config).QueryServer(_m)
}

// Update returns a builder for updating this Counter.
// Note that you need to call Counter.Unwrap() before calling this method if this Counter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Counter) Update() *CounterUpdateOne {
	return NewCounterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Counter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Counter) Unwrap() *Counter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Counter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Counter) String() string {
	var builder strings.Builder
	builder.WriteString("Counter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("window_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.WindowSec))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("last_seen=")
	builder.WriteString(_m.LastSeen.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Counters is a parsable slice of Counter.
type Counters []*Counter
