// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/rule"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RuleCreate is the builder for creating a Rule entity.
type RuleCreate struct {
	config
	mutation *RuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *RuleCreate) SetKind(v string) *RuleCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *RuleCreate) SetTarget(v string) *RuleCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetIsCidr sets the "is_cidr" field.
func (_c *RuleCreate) SetIsCidr(v bool) *RuleCreate {
	_c.mutation.SetIsCidr(v)
	return _c
}

// SetNillableIsCidr sets the "is_cidr" field if the given value is not nil.
func (_c *RuleCreate) SetNillableIsCidr(v *bool) *RuleCreate {
	if v != nil {
		_c.SetIsCidr(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *RuleCreate) SetReason(v string) *RuleCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *RuleCreate) SetNillableReason(v *string) *RuleCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RuleCreate) SetEnabled(v bool) *RuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RuleCreate) SetNillableEnabled(v *bool) *RuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RuleCreate) SetExpiresAt(v time.Time) *RuleCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableExpiresAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RuleCreate) SetCreatedAt(v time.Time) *RuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableCreatedAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RuleCreate) SetUpdatedAt(v time.Time) *RuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableUpdatedAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_c *RuleCreate) SetServerID(id int) *RuleCreate {
	_c.mutation.SetServerID(id)
	return _c
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_c *RuleCreate) SetNillableServerID(id *int) *RuleCreate {
	if id != nil {
		_c = _c.SetServerID(*id)
	}
	return _c
}

// SetServer sets the "server" edge to the Server entity.
func (_c *RuleCreate) SetServer(v *Server) *RuleCreate {
	return _c.SetServerID(v.ID)
}

// Mutation returns the RuleMutation object of the builder.
func (_c *RuleCreate) Mutation() *RuleMutation {
	return _c.mutation
}

// Save creates the Rule in the database.
func (_c *RuleCreate) Save(ctx context.Context) (*Rule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RuleCreate) SaveX(ctx context.Context) *Rule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RuleCreate) defaults() {
	if _, ok := _c.mutation.IsCidr(); !ok {
		v := rule.DefaultIsCidr
		_c.mutation.SetIsCidr(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := rule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RuleCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Rule.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := rule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Rule.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Rule.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := rule.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "Rule.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsCidr(); !ok {
		return &ValidationError{Name: "is_cidr", err: errors.New(`ent: missing required field "Rule.is_cidr"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Rule.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Rule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Rule.updated_at"`)}
	}
	return nil
}

func (_c *RuleCreate) sqlSave(ctx context.Context) (*Rule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RuleCreate) createSpec() (*Rule, *sqlgraph.CreateSpec) {
	var (
		_node = &Rule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rule.Table, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Rule
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(rule.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(rule.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.IsCidr(); ok {
		_spec.SetField(rule.FieldIsCidr, field.TypeBool, value)
		_node.IsCidr = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(rule.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(rule.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ServerTable,
			Columns: []string{rule.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.server_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rule.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuleUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *RuleCreate) OnConflict(opts ...sql.ConflictOption) *RuleUpsertOne {
	_c.conflict = opts
	return &RuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuleCreate) OnConflictColumns(columns ...string) *RuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuleUpsertOne{
		create: _c,
	}
}

type (
	// RuleUpsertOne is the builder for "upsert"-ing
	//  one Rule node.
	RuleUpsertOne struct {
		create *RuleCreate
	}

	// RuleUpsert is the "OnConflict" setter.
	RuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *RuleUpsert) SetKind(v string) *RuleUpsert {
	u.Set(rule.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *RuleUpsert) UpdateKind() *RuleUpsert {
	u.SetExcluded(rule.FieldKind)
	return u
}

// SetTarget sets the "target" field.
func (u *RuleUpsert) SetTarget(v string) *RuleUpsert {
	u.Set(rule.FieldTarget, v)
	return u
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *RuleUpsert) UpdateTarget() *RuleUpsert {
	u.SetExcluded(rule.FieldTarget)
	return u
}

// SetIsCidr sets the "is_cidr" field.
func (u *RuleUpsert) SetIsCidr(v bool) *RuleUpsert {
	u.Set(rule.FieldIsCidr, v)
	return u
}

// UpdateIsCidr sets the "is_cidr" field to the value that was provided on create.
func (u *RuleUpsert) UpdateIsCidr() *RuleUpsert {
	u.SetExcluded(rule.FieldIsCidr)
	return u
}

// SetReason sets the "reason" field.
func (u *RuleUpsert) SetReason(v string) *RuleUpsert {
	u.Set(rule.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RuleUpsert) UpdateReason() *RuleUpsert {
	u.SetExcluded(rule.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *RuleUpsert) ClearReason() *RuleUpsert {
	u.SetNull(rule.FieldReason)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *RuleUpsert) SetEnabled(v bool) *RuleUpsert {
	u.Set(rule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RuleUpsert) UpdateEnabled() *RuleUpsert {
	u.SetExcluded(rule.FieldEnabled)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *RuleUpsert) SetExpiresAt(v time.Time) *RuleUpsert {
	u.Set(rule.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RuleUpsert) UpdateExpiresAt() *RuleUpsert {
	u.SetExcluded(rule.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RuleUpsert) ClearExpiresAt() *RuleUpsert {
	u.SetNull(rule.FieldExpiresAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RuleUpsert) SetCreatedAt(v time.Time) *RuleUpsert {
	u.Set(rule.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RuleUpsert) UpdateCreatedAt() *RuleUpsert {
	u.SetExcluded(rule.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsert) SetUpdatedAt(v time.Time) *RuleUpsert {
	u.Set(rule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsert) UpdateUpdatedAt() *RuleUpsert {
	u.SetExcluded(rule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RuleUpsertOne) UpdateNewValues() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RuleUpsertOne) Ignore() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuleUpsertOne) DoNothing() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuleCreate.OnConflict
// documentation for more info.
func (u *RuleUpsertOne) Update(set func(*RuleUpsert)) *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *RuleUpsertOne) SetKind(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateKind() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateKind()
	})
}

// SetTarget sets the "target" field.
func (u *RuleUpsertOne) SetTarget(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateTarget() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTarget()
	})
}

// SetIsCidr sets the "is_cidr" field.
func (u *RuleUpsertOne) SetIsCidr(v bool) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetIsCidr(v)
	})
}

// UpdateIsCidr sets the "is_cidr" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateIsCidr() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateIsCidr()
	})
}

// SetReason sets the "reason" field.
func (u *RuleUpsertOne) SetReason(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateReason() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *RuleUpsertOne) ClearReason() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.ClearReason()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RuleUpsertOne) SetEnabled(v bool) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateEnabled() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RuleUpsertOne) SetExpiresAt(v time.Time) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateExpiresAt() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RuleUpsertOne) ClearExpiresAt() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.ClearExpiresAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RuleUpsertOne) SetCreatedAt(v time.Time) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateCreatedAt() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsertOne) SetUpdatedAt(v time.Time) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateUpdatedAt() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RuleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RuleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RuleCreateBulk is the builder for creating many Rule entities in bulk.
type RuleCreateBulk struct {
	config
	err      error
	builders []*RuleCreate
	conflict []sql.ConflictOption
}

// Save creates the Rule entities in the database.
func (_c *RuleCreateBulk) Save(ctx context.Context) ([]*Rule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Rule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RuleCreateBulk) SaveX(ctx context.Context) []*Rule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuleUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *RuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *RuleUpsertBulk {
	_c.conflict = opts
	return &RuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuleCreateBulk) OnConflictColumns(columns ...string) *RuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuleUpsertBulk{
		create: _c,
	}
}

// RuleUpsertBulk is the builder for "upsert"-ing
// a bulk of Rule nodes.
type RuleUpsertBulk struct {
	create *RuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RuleUpsertBulk) UpdateNewValues() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RuleUpsertBulk) Ignore() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuleUpsertBulk) DoNothing() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuleCreateBulk.OnConflict
// documentation for more info.
func (u *RuleUpsertBulk) Update(set func(*RuleUpsert)) *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *RuleUpsertBulk) SetKind(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateKind() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateKind()
	})
}

// SetTarget sets the "target" field.
func (u *RuleUpsertBulk) SetTarget(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateTarget() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTarget()
	})
}

// SetIsCidr sets the "is_cidr" field.
func (u *RuleUpsertBulk) SetIsCidr(v bool) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetIsCidr(v)
	})
}

// UpdateIsCidr sets the "is_cidr" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateIsCidr() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateIsCidr()
	})
}

// SetReason sets the "reason" field.
func (u *RuleUpsertBulk) SetReason(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateReason() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *RuleUpsertBulk) ClearReason() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.ClearReason()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RuleUpsertBulk) SetEnabled(v bool) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateEnabled() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RuleUpsertBulk) SetExpiresAt(v time.Time) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateExpiresAt() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RuleUpsertBulk) ClearExpiresAt() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.ClearExpiresAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RuleUpsertBulk) SetCreatedAt(v time.Time) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateCreatedAt() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsertBulk) SetUpdatedAt(v time.Time) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateUpdatedAt() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
