// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/internal"
	"mcproxy/internal/ent/predicate"
	"mcproxy/internal/ent/rule"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RuleUpdate is the builder for updating Rule entities.
type RuleUpdate struct {
	config
	hooks    []Hook
	mutation *RuleMutation
}

// Where appends a list predicates to the RuleUpdate builder.
func (_u *RuleUpdate) Where(ps ...predicate.Rule) *RuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *RuleUpdate) SetKind(v string) *RuleUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableKind(v *string) *RuleUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *RuleUpdate) SetTarget(v string) *RuleUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableTarget(v *string) *RuleUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetIsCidr sets the "is_cidr" field.
func (_u *RuleUpdate) SetIsCidr(v bool) *RuleUpdate {
	_u.mutation.SetIsCidr(v)
	return _u
}

// SetNillableIsCidr sets the "is_cidr" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableIsCidr(v *bool) *RuleUpdate {
	if v != nil {
		_u.SetIsCidr(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *RuleUpdate) SetReason(v string) *RuleUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableReason(v *string) *RuleUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *RuleUpdate) ClearReason() *RuleUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RuleUpdate) SetEnabled(v bool) *RuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableEnabled(v *bool) *RuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RuleUpdate) SetExpiresAt(v time.Time) *RuleUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableExpiresAt(v *time.Time) *RuleUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RuleUpdate) ClearExpiresAt() *RuleUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RuleUpdate) SetCreatedAt(v time.Time) *RuleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableCreatedAt(v *time.Time) *RuleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleUpdate) SetUpdatedAt(v time.Time) *RuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *RuleUpdate) SetServerID(id int) *RuleUpdate {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *RuleUpdate) SetNillableServerID(id *int) *RuleUpdate {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *RuleUpdate) SetServer(v *Server) *RuleUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the RuleMutation object of the builder.
func (_u *RuleUpdate) Mutation() *RuleMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *RuleUpdate) ClearServer() *RuleUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := rule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Rule.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := rule.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "Rule.target": %w`, err)}
		}
	}
	return nil
}

func (_u *RuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rule.Table, rule.Columns, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(rule.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(rule.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCidr(); ok {
		_spec.SetField(rule.FieldIsCidr, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(rule.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(rule.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(rule.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(rule.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(rule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ServerTable,
			Columns: []string{rule.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ServerTable,
			Columns: []string{rule.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Rule
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuleUpdateOne is the builder for updating a single Rule entity.
type RuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RuleMutation
}

// SetKind sets the "kind" field.
func (_u *RuleUpdateOne) SetKind(v string) *RuleUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableKind(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *RuleUpdateOne) SetTarget(v string) *RuleUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableTarget(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetIsCidr sets the "is_cidr" field.
func (_u *RuleUpdateOne) SetIsCidr(v bool) *RuleUpdateOne {
	_u.mutation.SetIsCidr(v)
	return _u
}

// SetNillableIsCidr sets the "is_cidr" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableIsCidr(v *bool) *RuleUpdateOne {
	if v != nil {
		_u.SetIsCidr(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *RuleUpdateOne) SetReason(v string) *RuleUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableReason(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *RuleUpdateOne) ClearReason() *RuleUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RuleUpdateOne) SetEnabled(v bool) *RuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableEnabled(v *bool) *RuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RuleUpdateOne) SetExpiresAt(v time.Time) *RuleUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableExpiresAt(v *time.Time) *RuleUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RuleUpdateOne) ClearExpiresAt() *RuleUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RuleUpdateOne) SetCreatedAt(v time.Time) *RuleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableCreatedAt(v *time.Time) *RuleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleUpdateOne) SetUpdatedAt(v time.Time) *RuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *RuleUpdateOne) SetServerID(id int) *RuleUpdateOne {
	_u.mutation.SetServerID(id)
	return _u
}

// SetNillableServerID sets the "server" edge to the Server entity by ID if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableServerID(id *int) *RuleUpdateOne {
	if id != nil {
		_u = _u.SetServerID(*id)
	}
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *RuleUpdateOne) SetServer(v *Server) *RuleUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the RuleMutation object of the builder.
func (_u *RuleUpdateOne) Mutation() *RuleMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *RuleUpdateOne) ClearServer() *RuleUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the RuleUpdate builder.
func (_u *RuleUpdateOne) Where(ps ...predicate.Rule) *RuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuleUpdateOne) Select(field string, fields ...string) *RuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Rule entity.
func (_u *RuleUpdateOne) Save(ctx context.Context) (*Rule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleUpdateOne) SaveX(ctx context.Context) *Rule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := rule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Rule.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := rule.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "Rule.target": %w`, err)}
		}
	}
	return nil
}

func (_u *RuleUpdateOne) sqlSave(ctx context.Context) (_node *Rule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rule.Table, rule.Columns, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Rule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rule.FieldID)
		for _, f := range fields {
			if !rule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(rule.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(rule.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCidr(); ok {
		_spec.SetField(rule.FieldIsCidr, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(rule.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(rule.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(rule.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(rule.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(rule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ServerTable,
			Columns: []string{rule.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ServerTable,
			Columns: []string{rule.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Rule
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Rule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
