// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mcproxy/internal/ent/accesspolicy"
	"mcproxy/internal/ent/audit"
	"mcproxy/internal/ent/counter"
	"mcproxy/internal/ent/rule"
	"mcproxy/internal/ent/schema"
	"mcproxy/internal/ent/server"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accesspolicyFields := schema.AccessPolicy{}.Fields()
	_ = accesspolicyFields
	// accesspolicyDescIPBurst10s is the schema descriptor for ip_burst_10s field.
	accesspolicyDescIPBurst10s := accesspolicyFields[0].Descriptor()
	// accesspolicy.DefaultIPBurst10s holds the default value on creation for the ip_burst_10s field.
	accesspolicy.DefaultIPBurst10s = accesspolicyDescIPBurst10s.Default.(int)
	// accesspolicyDescIPBurst60s is the schema descriptor for ip_burst_60s field.
	accesspolicyDescIPBurst60s := accesspolicyFields[1].Descriptor()
	// accesspolicy.DefaultIPBurst60s holds the default value on creation for the ip_burst_60s field.
	accesspolicy.DefaultIPBurst60s = accesspolicyDescIPBurst60s.Default.(int)
	// accesspolicyDescNameBurst10s is the schema descriptor for name_burst_10s field.
	accesspolicyDescNameBurst10s := accesspolicyFields[2].Descriptor()
	// accesspolicy.DefaultNameBurst10s holds the default value on creation for the name_burst_10s field.
	accesspolicy.DefaultNameBurst10s = accesspolicyDescNameBurst10s.Default.(int)
	// accesspolicyDescNameBurst60s is the schema descriptor for name_burst_60s field.
	accesspolicyDescNameBurst60s := accesspolicyFields[3].Descriptor()
	// accesspolicy.DefaultNameBurst60s holds the default value on creation for the name_burst_60s field.
	accesspolicy.DefaultNameBurst60s = accesspolicyDescNameBurst60s.Default.(int)
	// accesspolicyDescDenyFirst is the schema descriptor for deny_first field.
	accesspolicyDescDenyFirst := accesspolicyFields[4].Descriptor()
	// accesspolicy.DefaultDenyFirst holds the default value on creation for the deny_first field.
	accesspolicy.DefaultDenyFirst = accesspolicyDescDenyFirst.Default.(bool)
	// accesspolicyDescKickMessage is the schema descriptor for kick_message field.
	accesspolicyDescKickMessage := accesspolicyFields[5].Descriptor()
	// accesspolicy.DefaultKickMessage holds the default value on creation for the kick_message field.
	accesspolicy.DefaultKickMessage = accesspolicyDescKickMessage.Default.(string)
	// accesspolicyDescGeoMode is the schema descriptor for geo_mode field.
	accesspolicyDescGeoMode := accesspolicyFields[6].Descriptor()
	// accesspolicy.DefaultGeoMode holds the default value on creation for the geo_mode field.
	accesspolicy.DefaultGeoMode = accesspolicyDescGeoMode.Default.(string)
	// accesspolicyDescGeoList is the schema descriptor for geo_list field.
	accesspolicyDescGeoList := accesspolicyFields[7].Descriptor()
	// accesspolicy.DefaultGeoList holds the default value on creation for the geo_list field.
	accesspolicy.DefaultGeoList = accesspolicyDescGeoList.Default.([]string)
	// accesspolicyDescCreatedAt is the schema descriptor for created_at field.
	accesspolicyDescCreatedAt := accesspolicyFields[8].Descriptor()
	// accesspolicy.DefaultCreatedAt holds the default value on creation for the created_at field.
	accesspolicy.DefaultCreatedAt = accesspolicyDescCreatedAt.Default.(func() time.Time)
	// accesspolicyDescUpdatedAt is the schema descriptor for updated_at field.
	accesspolicyDescUpdatedAt := accesspolicyFields[9].Descriptor()
	// accesspolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	accesspolicy.DefaultUpdatedAt = accesspolicyDescUpdatedAt.Default.(func() time.Time)
	// accesspolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	accesspolicy.UpdateDefaultUpdatedAt = accesspolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditFields := schema.Audit{}.Fields()
	_ = auditFields
	// auditDescEvent is the schema descriptor for event field.
	auditDescEvent := auditFields[0].Descriptor()
	// audit.EventValidator is a validator for the "event" field. It is called by the builders before save.
	audit.EventValidator = auditDescEvent.Validators[0].(func(string) error)
	// auditDescDetails is the schema descriptor for details field.
	auditDescDetails := auditFields[2].Descriptor()
	// audit.DefaultDetails holds the default value on creation for the details field.
	audit.DefaultDetails = auditDescDetails.Default.(map[string]interface{})
	// auditDescCreatedAt is the schema descriptor for created_at field.
	auditDescCreatedAt := auditFields[3].Descriptor()
	// audit.DefaultCreatedAt holds the default value on creation for the created_at field.
	audit.DefaultCreatedAt = auditDescCreatedAt.Default.(func() time.Time)
	counterFields := schema.Counter{}.Fields()
	_ = counterFields
	// counterDescKind is the schema descriptor for kind field.
	counterDescKind := counterFields[0].Descriptor()
	// counter.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	counter.KindValidator = counterDescKind.Validators[0].(func(string) error)
	// counterDescKey is the schema descriptor for key field.
	counterDescKey := counterFields[1].Descriptor()
	// counter.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	counter.KeyValidator = counterDescKey.Validators[0].(func(string) error)
	// counterDescWindowSec is the schema descriptor for window_sec field.
	counterDescWindowSec := counterFields[2].Descriptor()
	// counter.WindowSecValidator is a validator for the "window_sec" field. It is called by the builders before save.
	counter.WindowSecValidator = counterDescWindowSec.Validators[0].(func(int) error)
	// counterDescCount is the schema descriptor for count field.
	counterDescCount := counterFields[3].Descriptor()
	// counter.DefaultCount holds the default value on creation for the count field.
	counter.DefaultCount = counterDescCount.Default.(int)
	// counter.CountValidator is a validator for the "count" field. It is called by the builders before save.
	counter.CountValidator = counterDescCount.Validators[0].(func(int) error)
	// counterDescLastSeen is the schema descriptor for last_seen field.
	counterDescLastSeen := counterFields[4].Descriptor()
	// counter.DefaultLastSeen holds the default value on creation for the last_seen field.
	counter.DefaultLastSeen = counterDescLastSeen.Default.(func() time.Time)
	// counterDescCreatedAt is the schema descriptor for created_at field.
	counterDescCreatedAt := counterFields[5].Descriptor()
	// counter.DefaultCreatedAt holds the default value on creation for the created_at field.
	counter.DefaultCreatedAt = counterDescCreatedAt.Default.(func() time.Time)
	// counterDescUpdatedAt is the schema descriptor for updated_at field.
	counterDescUpdatedAt := counterFields[6].Descriptor()
	// counter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	counter.DefaultUpdatedAt = counterDescUpdatedAt.Default.(func() time.Time)
	// counter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	counter.UpdateDefaultUpdatedAt = counterDescUpdatedAt.UpdateDefault.(func() time.Time)
	ruleFields := schema.Rule{}.Fields()
	_ = ruleFields
	// ruleDescKind is the schema descriptor for kind field.
	ruleDescKind := ruleFields[0].Descriptor()
	// rule.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	rule.KindValidator = ruleDescKind.Validators[0].(func(string) error)
	// ruleDescTarget is the schema descriptor for target field.
	ruleDescTarget := ruleFields[1].Descriptor()
	// rule.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	rule.TargetValidator = ruleDescTarget.Validators[0].(func(string) error)
	// ruleDescIsCidr is the schema descriptor for is_cidr field.
	ruleDescIsCidr := ruleFields[2].Descriptor()
	// rule.DefaultIsCidr holds the default value on creation for the is_cidr field.
	rule.DefaultIsCidr = ruleDescIsCidr.Default.(bool)
	// ruleDescEnabled is the schema descriptor for enabled field.
	ruleDescEnabled := ruleFields[4].Descriptor()
	// rule.DefaultEnabled holds the default value on creation for the enabled field.
	rule.DefaultEnabled = ruleDescEnabled.Default.(bool)
	// ruleDescCreatedAt is the schema descriptor for created_at field.
	ruleDescCreatedAt := ruleFields[6].Descriptor()
	// rule.DefaultCreatedAt holds the default value on creation for the created_at field.
	rule.DefaultCreatedAt = ruleDescCreatedAt.Default.(func() time.Time)
	// ruleDescUpdatedAt is the schema descriptor for updated_at field.
	ruleDescUpdatedAt := ruleFields[7].Descriptor()
	// rule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rule.DefaultUpdatedAt = ruleDescUpdatedAt.Default.(func() time.Time)
	// rule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rule.UpdateDefaultUpdatedAt = ruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	serverFields := schema.Server{}.Fields()
	_ = serverFields
	// serverDescName is the schema descriptor for name field.
	serverDescName := serverFields[0].Descriptor()
	// server.NameValidator is a validator for the "name" field. It is called by the builders before save.
	server.NameValidator = serverDescName.Validators[0].(func(string) error)
	// serverDescUpstream is the schema descriptor for upstream field.
	serverDescUpstream := serverFields[1].Descriptor()
	// server.UpstreamValidator is a validator for the "upstream" field. It is called by the builders before save.
	server.UpstreamValidator = serverDescUpstream.Validators[0].(func(string) error)
	// serverDescEnabled is the schema descriptor for enabled field.
	serverDescEnabled := serverFields[2].Descriptor()
	// server.DefaultEnabled holds the default value on creation for the enabled field.
	server.DefaultEnabled = serverDescEnabled.Default.(bool)
	// serverDescCreatedAt is the schema descriptor for created_at field.
	serverDescCreatedAt := serverFields[3].Descriptor()
	// server.DefaultCreatedAt holds the default value on creation for the created_at field.
	server.DefaultCreatedAt = serverDescCreatedAt.Default.(func() time.Time)
	// serverDescUpdatedAt is the schema descriptor for updated_at field.
	serverDescUpdatedAt := serverFields[4].Descriptor()
	// server.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	server.DefaultUpdatedAt = serverDescUpdatedAt.Default.(func() time.Time)
	// server.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	server.UpdateDefaultUpdatedAt = serverDescUpdatedAt.UpdateDefault.(func() time.Time)
}
