// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcproxy/internal/ent/accesspolicy"
	"mcproxy/internal/ent/audit"
	"mcproxy/internal/ent/counter"
	"mcproxy/internal/ent/internal"
	"mcproxy/internal/ent/predicate"
	"mcproxy/internal/ent/rule"
	"mcproxy/internal/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerUpdate is the builder for updating Server entities.
type ServerUpdate struct {
	config
	hooks    []Hook
	mutation *ServerMutation
}

// Where appends a list predicates to the ServerUpdate builder.
func (_u *ServerUpdate) Where(ps ...predicate.Server) *ServerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ServerUpdate) SetName(v string) *ServerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableName(v *string) *ServerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpstream sets the "upstream" field.
func (_u *ServerUpdate) SetUpstream(v string) *ServerUpdate {
	_u.mutation.SetUpstream(v)
	return _u
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableUpstream(v *string) *ServerUpdate {
	if v != nil {
		_u.SetUpstream(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ServerUpdate) SetEnabled(v bool) *ServerUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableEnabled(v *bool) *ServerUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ServerUpdate) SetCreatedAt(v time.Time) *ServerUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ServerUpdate) SetNillableCreatedAt(v *time.Time) *ServerUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServerUpdate) SetUpdatedAt(v time.Time) *ServerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPolicyIDs adds the "policies" edge to the AccessPolicy entity by IDs.
func (_u *ServerUpdate) AddPolicyIDs(ids ...int) *ServerUpdate {
	_u.mutation.AddPolicyIDs(ids...)
	return _u
}

// AddPolicies adds the "policies" edges to the AccessPolicy entity.
func (_u *ServerUpdate) AddPolicies(v ...*AccessPolicy) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPolicyIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (_u *ServerUpdate) AddRuleIDs(ids ...int) *ServerUpdate {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the Rule entity.
func (_u *ServerUpdate) AddRules(v ...*Rule) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// AddCounterIDs adds the "counters" edge to the Counter entity by IDs.
func (_u *ServerUpdate) AddCounterIDs(ids ...int) *ServerUpdate {
	_u.mutation.AddCounterIDs(ids...)
	return _u
}

// AddCounters adds the "counters" edges to the Counter entity.
func (_u *ServerUpdate) AddCounters(v ...*Counter) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCounterIDs(ids...)
}

// AddAuditIDs adds the "audits" edge to the Audit entity by IDs.
func (_u *ServerUpdate) AddAuditIDs(ids ...int) *ServerUpdate {
	_u.mutation.AddAuditIDs(ids...)
	return _u
}

// AddAudits adds the "audits" edges to the Audit entity.
func (_u *ServerUpdate) AddAudits(v ...*Audit) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditIDs(ids...)
}

// Mutation returns the ServerMutation object of the builder.
func (_u *ServerUpdate) Mutation() *ServerMutation {
	return _u.mutation
}

// ClearPolicies clears all "policies" edges to the AccessPolicy entity.
func (_u *ServerUpdate) ClearPolicies() *ServerUpdate {
	_u.mutation.ClearPolicies()
	return _u
}

// RemovePolicyIDs removes the "policies" edge to AccessPolicy entities by IDs.
func (_u *ServerUpdate) RemovePolicyIDs(ids ...int) *ServerUpdate {
	_u.mutation.RemovePolicyIDs(ids...)
	return _u
}

// RemovePolicies removes "policies" edges to AccessPolicy entities.
func (_u *ServerUpdate) RemovePolicies(v ...*AccessPolicy) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePolicyIDs(ids...)
}

// ClearRules clears all "rules" edges to the Rule entity.
func (_u *ServerUpdate) ClearRules() *ServerUpdate {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (_u *ServerUpdate) RemoveRuleIDs(ids ...int) *ServerUpdate {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to Rule entities.
func (_u *ServerUpdate) RemoveRules(v ...*Rule) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// ClearCounters clears all "counters" edges to the Counter entity.
func (_u *ServerUpdate) ClearCounters() *ServerUpdate {
	_u.mutation.ClearCounters()
	return _u
}

// RemoveCounterIDs removes the "counters" edge to Counter entities by IDs.
func (_u *ServerUpdate) RemoveCounterIDs(ids ...int) *ServerUpdate {
	_u.mutation.RemoveCounterIDs(ids...)
	return _u
}

// RemoveCounters removes "counters" edges to Counter entities.
func (_u *ServerUpdate) RemoveCounters(v ...*Counter) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCounterIDs(ids...)
}

// ClearAudits clears all "audits" edges to the Audit entity.
func (_u *ServerUpdate) ClearAudits() *ServerUpdate {
	_u.mutation.ClearAudits()
	return _u
}

// RemoveAuditIDs removes the "audits" edge to Audit entities by IDs.
func (_u *ServerUpdate) RemoveAuditIDs(ids ...int) *ServerUpdate {
	_u.mutation.RemoveAuditIDs(ids...)
	return _u
}

// RemoveAudits removes "audits" edges to Audit entities.
func (_u *ServerUpdate) RemoveAudits(v ...*Audit) *ServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := server.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := server.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Server.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Upstream(); ok {
		if err := server.UpstreamValidator(v); err != nil {
			return &ValidationError{Name: "upstream", err: fmt.Errorf(`ent: validator failed for field "Server.upstream": %w`, err)}
		}
	}
	return nil
}

func (_u *ServerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(server.Table, server.Columns, sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(server.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Upstream(); ok {
		_spec.SetField(server.FieldUpstream, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(server.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(server.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(server.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.PoliciesTable,
			Columns: []string{server.PoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPoliciesIDs(); len(nodes) > 0 && !_u.mutation.PoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.PoliciesTable,
			Columns: []string{server.PoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.PoliciesTable,
			Columns: []string{server.PoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.RulesTable,
			Columns: []string{server.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.RulesTable,
			Columns: []string{server.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.RulesTable,
			Columns: []string{server.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.CountersTable,
			Columns: []string{server.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCountersIDs(); len(nodes) > 0 && !_u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.CountersTable,
			Columns: []string{server.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CountersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.CountersTable,
			Columns: []string{server.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.AuditsTable,
			Columns: []string{server.AuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditsIDs(); len(nodes) > 0 && !_u.mutation.AuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.AuditsTable,
			Columns: []string{server.AuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.AuditsTable,
			Columns: []string{server.AuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Server
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{server.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServerUpdateOne is the builder for updating a single Server entity.
type ServerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServerMutation
}

// SetName sets the "name" field.
func (_u *ServerUpdateOne) SetName(v string) *ServerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableName(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpstream sets the "upstream" field.
func (_u *ServerUpdateOne) SetUpstream(v string) *ServerUpdateOne {
	_u.mutation.SetUpstream(v)
	return _u
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableUpstream(v *string) *ServerUpdateOne {
	if v != nil {
		_u.SetUpstream(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ServerUpdateOne) SetEnabled(v bool) *ServerUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableEnabled(v *bool) *ServerUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ServerUpdateOne) SetCreatedAt(v time.Time) *ServerUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ServerUpdateOne) SetNillableCreatedAt(v *time.Time) *ServerUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServerUpdateOne) SetUpdatedAt(v time.Time) *ServerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPolicyIDs adds the "policies" edge to the AccessPolicy entity by IDs.
func (_u *ServerUpdateOne) AddPolicyIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.AddPolicyIDs(ids...)
	return _u
}

// AddPolicies adds the "policies" edges to the AccessPolicy entity.
func (_u *ServerUpdateOne) AddPolicies(v ...*AccessPolicy) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPolicyIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (_u *ServerUpdateOne) AddRuleIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the Rule entity.
func (_u *ServerUpdateOne) AddRules(v ...*Rule) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// AddCounterIDs adds the "counters" edge to the Counter entity by IDs.
func (_u *ServerUpdateOne) AddCounterIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.AddCounterIDs(ids...)
	return _u
}

// AddCounters adds the "counters" edges to the Counter entity.
func (_u *ServerUpdateOne) AddCounters(v ...*Counter) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCounterIDs(ids...)
}

// AddAuditIDs adds the "audits" edge to the Audit entity by IDs.
func (_u *ServerUpdateOne) AddAuditIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.AddAuditIDs(ids...)
	return _u
}

// AddAudits adds the "audits" edges to the Audit entity.
func (_u *ServerUpdateOne) AddAudits(v ...*Audit) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditIDs(ids...)
}

// Mutation returns the ServerMutation object of the builder.
func (_u *ServerUpdateOne) Mutation() *ServerMutation {
	return _u.mutation
}

// ClearPolicies clears all "policies" edges to the AccessPolicy entity.
func (_u *ServerUpdateOne) ClearPolicies() *ServerUpdateOne {
	_u.mutation.ClearPolicies()
	return _u
}

// RemovePolicyIDs removes the "policies" edge to AccessPolicy entities by IDs.
func (_u *ServerUpdateOne) RemovePolicyIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.RemovePolicyIDs(ids...)
	return _u
}

// RemovePolicies removes "policies" edges to AccessPolicy entities.
func (_u *ServerUpdateOne) RemovePolicies(v ...*AccessPolicy) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePolicyIDs(ids...)
}

// ClearRules clears all "rules" edges to the Rule entity.
func (_u *ServerUpdateOne) ClearRules() *ServerUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (_u *ServerUpdateOne) RemoveRuleIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to Rule entities.
func (_u *ServerUpdateOne) RemoveRules(v ...*Rule) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// ClearCounters clears all "counters" edges to the Counter entity.
func (_u *ServerUpdateOne) ClearCounters() *ServerUpdateOne {
	_u.mutation.ClearCounters()
	return _u
}

// RemoveCounterIDs removes the "counters" edge to Counter entities by IDs.
func (_u *ServerUpdateOne) RemoveCounterIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.RemoveCounterIDs(ids...)
	return _u
}

// RemoveCounters removes "counters" edges to Counter entities.
func (_u *ServerUpdateOne) RemoveCounters(v ...*Counter) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCounterIDs(ids...)
}

// ClearAudits clears all "audits" edges to the Audit entity.
func (_u *ServerUpdateOne) ClearAudits() *ServerUpdateOne {
	_u.mutation.ClearAudits()
	return _u
}

// RemoveAuditIDs removes the "audits" edge to Audit entities by IDs.
func (_u *ServerUpdateOne) RemoveAuditIDs(ids ...int) *ServerUpdateOne {
	_u.mutation.RemoveAuditIDs(ids...)
	return _u
}

// RemoveAudits removes "audits" edges to Audit entities.
func (_u *ServerUpdateOne) RemoveAudits(v ...*Audit) *ServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditIDs(ids...)
}

// Where appends a list predicates to the ServerUpdate builder.
func (_u *ServerUpdateOne) Where(ps ...predicate.Server) *ServerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServerUpdateOne) Select(field string, fields ...string) *ServerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Server entity.
func (_u *ServerUpdateOne) Save(ctx context.Context) (*Server, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerUpdateOne) SaveX(ctx context.Context) *Server {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := server.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := server.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Server.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Upstream(); ok {
		if err := server.UpstreamValidator(v); err != nil {
			return &ValidationError{Name: "upstream", err: fmt.Errorf(`ent: validator failed for field "Server.upstream": %w`, err)}
		}
	}
	return nil
}

func (_u *ServerUpdateOne) sqlSave(ctx context.Context) (_node *Server, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(server.Table, server.Columns, sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Server.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, server.FieldID)
		for _, f := range fields {
			if !server.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != server.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(server.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Upstream(); ok {
		_spec.SetField(server.FieldUpstream, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(server.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(server.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(server.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.PoliciesTable,
			Columns: []string{server.PoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPoliciesIDs(); len(nodes) > 0 && !_u.mutation.PoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.PoliciesTable,
			Columns: []string{server.PoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.PoliciesTable,
			Columns: []string{server.PoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.AccessPolicy
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.RulesTable,
			Columns: []string{server.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.RulesTable,
			Columns: []string{server.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.RulesTable,
			Columns: []string{server.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Rule
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.CountersTable,
			Columns: []string{server.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCountersIDs(); len(nodes) > 0 && !_u.mutation.CountersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.CountersTable,
			Columns: []string{server.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CountersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.CountersTable,
			Columns: []string{server.CountersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(counter.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Counter
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.AuditsTable,
			Columns: []string{server.AuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditsIDs(); len(nodes) > 0 && !_u.mutation.AuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.AuditsTable,
			Columns: []string{server.AuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.AuditsTable,
			Columns: []string{server.AuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Audit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Server
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Server{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{server.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
