// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mcproxy/internal/ent/server"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Server is the model entity for the Server schema.
type Server struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Upstream holds the value of the "upstream" field.
	Upstream string `json:"upstream,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServerQuery when eager-loading is set.
	Edges        ServerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServerEdges holds the relations/edges for other nodes in the graph.
type ServerEdges struct {
	// Policies holds the value of the policies edge.
	Policies []*AccessPolicy `json:"policies,omitempty"`
	// Rules holds the value of the rules edge.
	Rules []*Rule `json:"rules,omitempty"`
	// Counters holds the value of the counters edge.
	Counters []*Counter `json:"counters,omitempty"`
	// Audits holds the value of the audits edge.
	Audits []*Audit `json:"audits,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PoliciesOrErr returns the Policies value or an error if the edge
// was not loaded in eager-loading.
func (e ServerEdges) PoliciesOrErr() ([]*AccessPolicy, error) {
	if e.loadedTypes[0] {
		return e.Policies, nil
	}
	return nil, &NotLoadedError{edge: "policies"}
}

// RulesOrErr returns the Rules value or an error if the edge
// was not loaded in eager-loading.
func (e ServerEdges) RulesOrErr() ([]*Rule, error) {
	if e.loadedTypes[1] {
		return e.Rules, nil
	}
	return nil, &NotLoadedError{edge: "rules"}
}

// CountersOrErr returns the Counters value or an error if the edge
// was not loaded in eager-loading.
func (e ServerEdges) CountersOrErr() ([]*Counter, error) {
	if e.loadedTypes[2] {
		return e.Counters, nil
	}
	return nil, &NotLoadedError{edge: "counters"}
}

// AuditsOrErr returns the Audits value or an error if the edge
// was not loaded in eager-loading.
func (e ServerEdges) AuditsOrErr() ([]*Audit, error) {
	if e.loadedTypes[3] {
		return e.Audits, nil
	}
	return nil, &NotLoadedError{edge: "audits"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Server) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case server.FieldEnabled:
			values[i] = new(sql.NullBool)
		case server.FieldID:
			values[i] = new(sql.NullInt64)
		case server.FieldName, server.FieldUpstream:
			values[i] = new(sql.NullString)
		case server.FieldCreatedAt, server.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Server fields.
func (_m *Server) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case server.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case server.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case server.FieldUpstream:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream", values[i])
			} else if value.Valid {
				_m.Upstream = value.String
			}
		case server.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case server.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case server.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Server.
// This includes values selected through modifiers, order, etc.
func (_m *Server) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPolicies queries the "policies" edge of the Server entity.
func (_m *Server) QueryPolicies() *AccessPolicyQuery {
	return NewServerClient(_m.config).QueryPolicies(_m)
}

// QueryRules queries the "rules" edge of the Server entity.
func (_m *Server) QueryRules() *RuleQuery {
	return NewServerClient(_m.config).QueryRules(_m)
}

// QueryCounters queries the "counters" edge of the Server entity.
func (_m *Server) QueryCounters() *CounterQuery {
	return NewServerClient(_m.config).QueryCounters(_m)
}

// QueryAudits queries the "audits" edge of the Server entity.
func (_m *Server) QueryAudits() *AuditQuery {
	return NewServerClient(_m.config).QueryAudits(_m)
}

// Update returns a builder for updating this Server.
// Note that you need to call Server.Unwrap() before calling this method if this Server
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Server) Update() *ServerUpdateOne {
	return NewServerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Server entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Server) Unwrap() *Server {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Server is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Server) String() string {
	var builder strings.Builder
	builder.WriteString("Server(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("upstream=")
	builder.WriteString(_m.Upstream)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Servers is a parsable slice of Server.
type Servers []*Server
