// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessPolicy is the predicate function for accesspolicy builders.
type AccessPolicy func(*sql.Selector)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// Counter is the predicate function for counter builders.
type Counter func(*sql.Selector)

// Rule is the predicate function for rule builders.
type Rule func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)
