// Code generated by ent, DO NOT EDIT.

package server

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the server type in the database.
	Label = "server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUpstream holds the string denoting the upstream field in the database.
	FieldUpstream = "upstream"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePolicies holds the string denoting the policies edge name in mutations.
	EdgePolicies = "policies"
	// EdgeRules holds the string denoting the rules edge name in mutations.
	EdgeRules = "rules"
	// EdgeCounters holds the string denoting the counters edge name in mutations.
	EdgeCounters = "counters"
	// EdgeAudits holds the string denoting the audits edge name in mutations.
	EdgeAudits = "audits"
	// Table holds the table name of the server in the database.
	Table = "servers"
	// PoliciesTable is the table that holds the policies relation/edge.
	PoliciesTable = "access_policies"
	// PoliciesInverseTable is the table name for the AccessPolicy entity.
	// It exists in this package in order to avoid circular dependency with the "accesspolicy" package.
	PoliciesInverseTable = "access_policies"
	// PoliciesColumn is the table column denoting the policies relation/edge.
	PoliciesColumn = "server_policies"
	// RulesTable is the table that holds the rules relation/edge.
	RulesTable = "rules"
	// RulesInverseTable is the table name for the Rule entity.
	// It exists in this package in order to avoid circular dependency with the "rule" package.
	RulesInverseTable = "rules"
	// RulesColumn is the table column denoting the rules relation/edge.
	RulesColumn = "server_rules"
	// CountersTable is the table that holds the counters relation/edge.
	CountersTable = "counters"
	// CountersInverseTable is the table name for the Counter entity.
	// It exists in this package in order to avoid circular dependency with the "counter" package.
	CountersInverseTable = "counters"
	// CountersColumn is the table column denoting the counters relation/edge.
	CountersColumn = "server_counters"
	// AuditsTable is the table that holds the audits relation/edge.
	AuditsTable = "audits"
	// AuditsInverseTable is the table name for the Audit entity.
	// It exists in this package in order to avoid circular dependency with the "audit" package.
	AuditsInverseTable = "audits"
	// AuditsColumn is the table column denoting the audits relation/edge.
	AuditsColumn = "server_audits"
)

// Columns holds all SQL columns for server fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldUpstream,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// UpstreamValidator is a validator for the "upstream" field. It is called by the builders before save.
	UpstreamValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Server queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByUpstream orders the results by the upstream field.
func ByUpstream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstream, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPoliciesCount orders the results by policies count.
func ByPoliciesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPoliciesStep(), opts...)
	}
}

// ByPolicies orders the results by policies terms.
func ByPolicies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPoliciesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRulesCount orders the results by rules count.
func ByRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRulesStep(), opts...)
	}
}

// ByRules orders the results by rules terms.
func ByRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCountersCount orders the results by counters count.
func ByCountersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCountersStep(), opts...)
	}
}

// ByCounters orders the results by counters terms.
func ByCounters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCountersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuditsCount orders the results by audits count.
func ByAuditsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuditsStep(), opts...)
	}
}

// ByAudits orders the results by audits terms.
func ByAudits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPoliciesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PoliciesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PoliciesTable, PoliciesColumn),
	)
}
func newRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RulesTable, RulesColumn),
	)
}
func newCountersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CountersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CountersTable, CountersColumn),
	)
}
func newAuditsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuditsTable, AuditsColumn),
	)
}
