// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"

	"mcproxy/internal/ent"

	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns a formatted wrapped Allow decision.
func Allowf(format string, a ...any) error {
	return privacy.Allowf(format, a...)
}

// Denyf returns a formatted wrapped Deny decision.
func Denyf(format string, a ...any) error {
	return privacy.Denyf(format, a...)
}

// Skipf returns a formatted wrapped Skip decision.
func Skipf(format string, a ...any) error {
	return privacy.Skipf(format, a...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
	// MutationRuleFunc type is an adapter which allows the use of
	// ordinary functions as mutation rules.
	MutationRuleFunc = privacy.MutationRuleFunc

	// QueryMutationRule is an interface which groups query and mutation rules.
	QueryMutationRule = privacy.QueryMutationRule
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, ent.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	return f(ctx, q)
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return privacy.AlwaysAllowRule()
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return privacy.AlwaysDenyRule()
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return privacy.ContextQueryMutationRule(eval)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op ent.Op) MutationRule {
	return privacy.OnMutationOperation(rule, op)
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op ent.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m ent.Mutation) error {
		return Denyf("ent/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The AccessPolicyQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type AccessPolicyQueryRuleFunc func(context.Context, *ent.AccessPolicyQuery) error

// EvalQuery return f(ctx, q).
func (f AccessPolicyQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccessPolicyQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.AccessPolicyQuery", q)
}

// The AccessPolicyMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type AccessPolicyMutationRuleFunc func(context.Context, *ent.AccessPolicyMutation) error

// EvalMutation calls f(ctx, m).
func (f AccessPolicyMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.AccessPolicyMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.AccessPolicyMutation", m)
}

// The AuditQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type AuditQueryRuleFunc func(context.Context, *ent.AuditQuery) error

// EvalQuery return f(ctx, q).
func (f AuditQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuditQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.AuditQuery", q)
}

// The AuditMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type AuditMutationRuleFunc func(context.Context, *ent.AuditMutation) error

// EvalMutation calls f(ctx, m).
func (f AuditMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.AuditMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.AuditMutation", m)
}

// The CounterQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type CounterQueryRuleFunc func(context.Context, *ent.CounterQuery) error

// EvalQuery return f(ctx, q).
func (f CounterQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CounterQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.CounterQuery", q)
}

// The CounterMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type CounterMutationRuleFunc func(context.Context, *ent.CounterMutation) error

// EvalMutation calls f(ctx, m).
func (f CounterMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.CounterMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.CounterMutation", m)
}

// The RuleQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type RuleQueryRuleFunc func(context.Context, *ent.RuleQuery) error

// EvalQuery return f(ctx, q).
func (f RuleQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RuleQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.RuleQuery", q)
}

// The RuleMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type RuleMutationRuleFunc func(context.Context, *ent.RuleMutation) error

// EvalMutation calls f(ctx, m).
func (f RuleMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.RuleMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.RuleMutation", m)
}

// The ServerQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ServerQueryRuleFunc func(context.Context, *ent.ServerQuery) error

// EvalQuery return f(ctx, q).
func (f ServerQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ServerQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ServerQuery", q)
}

// The ServerMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ServerMutationRuleFunc func(context.Context, *ent.ServerMutation) error

// EvalMutation calls f(ctx, m).
func (f ServerMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ServerMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ServerMutation", m)
}
